
import { GameState, BoardSpace, GameStage, Dynasty, Item } from './types';

// FIX: Add INITIAL_GAME_STATE export.
export const INITIAL_GAME_STATE: GameState = {
  stage: GameStage.DynastySelection,
  dynasty: null,
  players: [],
  currentPlayerIndex: 0,
  board: [],
  diceValues: [0, 0],
  lastDiceValues: [0, 0],
  isRolling: false,
  isMoving: false,
  stepsToMove: 0,
  showCityModal: false,
  showEventModal: false,
  isFetchingEvent: false,
  eventDescription: '',
  lastGoldChange: undefined,
  error: null,
  tollPaymentInfo: null,
  salaryPaymentInfo: null,
  justEscapedIsland: false,
  victoryCondition: null,
  gameStartTime: null,
  winner: null,
  winningReason: null,
  showOpponentCityModal: false,
  showStealMoneyModal: false,
  showStealPropertyModal: false,
  eventForSteal: null,
  specialSpaces: {
    x2: [],
    x3: [],
  },
  toastMessage: null,
  turnShouldEnd: false,
  shouldProcessTurnAfterEvent: false,
  showTravelModal: false,
  showUpgradeModal: false,
  justTraveled: false,
  justStayedOnIsland: false,
  treasury: 0,
  treasuryTaxAmount: 80,
  treasuryVisitCount: 0,
  turnCount: 0,
  showItemModal: false,
  acquiredItem: null,
};

export const PLAYER_COLORS = [
    'bg-red-500',
    'bg-blue-500',
    'bg-green-500',
    'bg-yellow-500',
];

export const PLAYER_EMOJIS = ['🚗', '✈️', '🚀', '🚆', '🚌', '🚂'];

export const CUTE_AI_NAMES = ['꿈꾸는 돌고래', '행복한 쿼카', '미소짓는 알파카', '명랑한 다람쥐', '상냥한 사슴', '춤추는 펭귄'];

export const DYNASTY_NAMES: Record<Dynasty, string> = {
    GOJOSEON_THREE_KINGDOMS: '고조선 & 삼국시대',
    UNIFIED_SILLA_BALHAE: '통일신라 & 발해',
    LATER_THREE_KINGDOMS: '후삼국시대',
    GORYEO: '고려시대',
    JOSEON: '조선시대',
    MODERN_CONTEMPORARY: '대한민국 근현대사'
};

export const ITEMS: Item[] = [
  // Normal Items
  // GOJOSEON_THREE_KINGDOMS
  { name: '청동 방울', description: '제사장의 권위를 상징하는 방울. 모든 통행료 수입이 10% 증가합니다.', effect: 'TOLL_INCREASE_10', icon: '🔔', dynasty: ['GOJOSEON_THREE_KINGDOMS'] },
  { name: '고인돌의 기운', description: '거대한 돌에 깃든 조상의 힘으로, 국고에 내는 세금을 60% 감면받습니다.', effect: 'TREASURY_EXEMPTION', icon: '🗿', dynasty: ['GOJOSEON_THREE_KINGDOMS'] },
  { name: '가야 철갑', description: '견고한 철갑옷. 상대방에게 지불하는 모든 통행료가 10% 감소합니다.', effect: 'TOLL_DISCOUNT_10', icon: '🛡️', dynasty: ['GOJOSEON_THREE_KINGDOMS'] },
  { name: '칠지도', description: '백제가 왜왕에게 하사한 신비로운 검. 월급이 10% 증가합니다.', effect: 'SALARY_BONUS_10', icon: '⚔️', dynasty: ['GOJOSEON_THREE_KINGDOMS'] },
  { name: '거문고', description: '왕산악이 만든 악기. 아름다운 소리가 무인도에서의 외로움을 달래 체류 기간을 1턴 줄여줍니다.', effect: 'ISLAND_STAY_REDUCED_1', icon: '🎶', dynasty: ['GOJOSEON_THREE_KINGDOMS'] },
  { name: '토지 측량 깃발', description: '효율적인 토지 관리로, 도시 구매 비용을 10% 할인받습니다.', effect: 'LAND_PURCHASE_DISCOUNT_10', icon: '📝', dynasty: ['GOJOSEON_THREE_KINGDOMS'] },
  // UNIFIED_SILLA_BALHAE
  { name: '만파식적', description: '세상의 모든 걱정을 잠재우는 신비한 피리. 모든 통행료 수입이 10% 증가합니다.', effect: 'TOLL_INCREASE_10', icon: '🎍', dynasty: ['UNIFIED_SILLA_BALHAE'] },
  { name: '주령구', description: '신라 귀족의 놀이 기구. 벌칙 대신 행운을 가져와 국고에 내는 세금을 60% 감면받습니다.', effect: 'TREASURY_EXEMPTION', icon: '🎲', dynasty: ['UNIFIED_SILLA_BALHAE'] },
  { name: '발해의 담비 가죽', description: '북방의 귀한 특산품. 교역을 통해 상대에게 내는 통행료가 10% 감소합니다.', effect: 'TOLL_DISCOUNT_10', icon: '🐾', dynasty: ['UNIFIED_SILLA_BALHAE'] },
  { name: '해동성국의 위상', description: '바다 동쪽의 융성한 나라, 발해의 명성 덕분에 월급이 10% 증가합니다.', effect: 'SALARY_BONUS_10', icon: '🌊', dynasty: ['UNIFIED_SILLA_BALHAE'] },
  { name: '무구정광대다라니경', description: '세계 최고(最古)의 목판 인쇄물. 부처의 가호로 무인도 체류 기간이 1턴 줄어듭니다.', effect: 'ISLAND_STAY_REDUCED_1', icon: '📜', dynasty: ['UNIFIED_SILLA_BALHAE'] },
  { name: '촌락 문서', description: '효율적인 토지 관리로, 도시 구매 비용을 10% 할인받습니다.', effect: 'LAND_PURCHASE_DISCOUNT_10', icon: '📝', dynasty: ['UNIFIED_SILLA_BALHAE'] },
  // LATER_THREE_KINGDOMS
  { name: '관심법', description: '궁예의 신비한 능력. 상대의 마음을 읽어 통행료 수입을 10% 증가시킵니다.', effect: 'TOLL_INCREASE_10', icon: '👁️', dynasty: ['LATER_THREE_KINGDOMS'] },
  { name: '왕건의 포용력', description: '모든 호족을 아우르는 리더십. 민심을 얻어 국고에 내는 세금을 60% 감면받습니다.', effect: 'TREASURY_EXEMPTION', icon: '🤝', dynasty: ['LATER_THREE_KINGDOMS'] },
  { name: '견훤의 외교술', description: '중국과의 외교로 얻은 신뢰. 상대에게 지불하는 통행료가 10% 감소합니다.', effect: 'TOLL_DISCOUNT_10', icon: '✉️', dynasty: ['LATER_THREE_KINGDOMS'] },
  { name: '해상왕국의 꿈', description: '왕건의 해상 세력이 교역로를 장악하여 월급이 10% 증가합니다.', effect: 'SALARY_BONUS_10', icon: '⚓', dynasty: ['LATER_THREE_KINGDOMS'] },
  { name: '팔공산의 가호', description: '신숭겸의 충절이 깃든 산의 정기. 위기를 빠르게 벗어나 무인도 체류 기간이 1턴 줄어듭니다.', effect: 'ISLAND_STAY_REDUCED_1', icon: '⛰️', dynasty: ['LATER_THREE_KINGDOMS'] },
  { name: '호족의 인장', description: '효율적인 토지 관리로, 도시 구매 비용을 10% 할인받습니다.', effect: 'LAND_PURCHASE_DISCOUNT_10', icon: '📝', dynasty: ['LATER_THREE_KINGDOMS'] },
  // GORYEO
  { name: '상감청자', description: '고려 예술의 정수. 그 아름다움에 감탄한 방문객들이 통행료를 10% 더 냅니다.', effect: 'TOLL_INCREASE_10', icon: '🏺', dynasty: ['GORYEO'] },
  { name: '팔만대장경 목판', description: '부처의 힘이 깃들어 있어, 국고에 내야 할 세금을 60% 감면받습니다.', effect: 'TREASURY_EXEMPTION', icon: '📖', dynasty: ['GORYEO'] },
  { name: '벽란도의 상인', description: '국제 무역항의 유능한 상인 덕분에 통행료 지불 시 10%를 할인받습니다.', effect: 'TOLL_DISCOUNT_10', icon: '🚢', dynasty: ['GORYEO'] },
  { name: '고려 인삼', description: '세계적으로 유명한 고려의 특산품. 수출 수익으로 월급이 10% 증가합니다.', effect: 'SALARY_BONUS_10', icon: '🌿', dynasty: ['GORYEO'] },
  { name: '삼별초의 깃발', description: '꺾이지 않는 항쟁의 정신. 어떤 어려움도 빠르게 극복하여 무인도 체류 기간을 1턴 줄여줍니다.', effect: 'ISLAND_STAY_REDUCED_1', icon: '🚩', dynasty: ['GORYEO'] },
  { name: '양안 사본', description: '효율적인 토지 관리로, 도시 구매 비용을 10% 할인받습니다.', effect: 'LAND_PURCHASE_DISCOUNT_10', icon: '📝', dynasty: ['GORYEO'] },
  // JOSEON
  { name: '훈민정음 해례본', description: '백성을 위한 글자의 가치. 모든 땅의 통행료 수입이 10% 증가합니다.', effect: 'TOLL_INCREASE_10', icon: '✍️', dynasty: ['JOSEON'] },
  { name: '균역법', description: '백성의 세금 부담을 줄여주는 법. 국고에 내야 할 세금을 60% 감면받습니다.', effect: 'TREASURY_EXEMPTION', icon: '📜', dynasty: ['JOSEON'] },
  { name: '거중기', description: '정약용이 발명한 기계. 효율적인 기술력으로 통행료 지불액을 10% 감소시킵니다.', effect: 'TOLL_DISCOUNT_10', icon: '🏗️', dynasty: ['JOSEON'] },
  { name: '앙부일구', description: '조선의 뛰어난 과학 기술력. 시간의 흐름을 정확히 읽어 월급이 10% 증가합니다.', effect: 'SALARY_BONUS_10', icon: '☀️', dynasty: ['JOSEON'] },
  { name: '난중일기', description: '이순신 장군의 기록. 위기를 극복하는 지혜를 얻어 무인도 체류 기간이 1턴 줄어듭니다.', effect: 'ISLAND_STAY_REDUCED_1', icon: '📓', dynasty: ['JOSEON'] },
  { name: '지계', description: '효율적인 토지 관리로, 도시 구매 비용을 10% 할인받습니다.', effect: 'LAND_PURCHASE_DISCOUNT_10', icon: '📝', dynasty: ['JOSEON'] },
  // MODERN_CONTEMPORARY
  { name: '금모으기 운동 증서', description: '국난 극복의 상징. 국민의 염원이 담겨 통행료 수입이 10% 증가합니다.', effect: 'TOLL_INCREASE_10', icon: '🏅', dynasty: ['MODERN_CONTEMPORARY'] },
  { name: '새마을운동 깃발', description: '근면, 자조, 협동 정신. 국가 발전에 기여하여 국고에 내는 세금을 60% 감면받습니다.', effect: 'TREASURY_EXEMPTION', icon: '🌾', dynasty: ['MODERN_CONTEMPORARY'] },
  { name: '88올림픽 호돌이', description: '세계적인 축제의 마스코트. 우호적인 분위기 속에서 통행료를 10% 할인받습니다.', effect: 'TOLL_DISCOUNT_10', icon: '🐯', dynasty: ['MODERN_CONTEMPORARY'] },
  { name: 'K-POP 앨범', description: '전 세계를 휩쓴 한류 열풍. 저작권 수입으로 월급이 10% 증가합니다.', effect: 'SALARY_BONUS_10', icon: '🎤', dynasty: ['MODERN_CONTEMPORARY'] },
  { name: '최초의 국산 휴대폰', description: 'IT 강국의 시작. 빠른 정보력으로 무인도에서 1턴 빨리 탈출합니다.', effect: 'ISLAND_STAY_REDUCED_1', icon: '📱', dynasty: ['MODERN_CONTEMPORARY'] },
  { name: '토지개혁문서', description: '효율적인 토지 관리로, 도시 구매 비용을 10% 할인받습니다.', effect: 'LAND_PURCHASE_DISCOUNT_10', icon: '📝', dynasty: ['MODERN_CONTEMPORARY'] },

  // Advanced Items
  // GOJOSEON_THREE_KINGDOMS
  { name: '✨ 빛나는 청동 방울', description: '강력한 제사장의 권위를 상징하는 방울. 모든 통행료 수입이 20% 증가합니다.', effect: 'TOLL_INCREASE_20', icon: '🔔', dynasty: ['GOJOSEON_THREE_KINGDOMS'], isAdvanced: true },
  { name: '✨ 견고한 가야 철갑', description: '장인의 혼이 깃든 철갑옷. 상대방에게 지불하는 모든 통행료가 20% 감소합니다.', effect: 'TOLL_DISCOUNT_20', icon: '🛡️', dynasty: ['GOJOSEON_THREE_KINGDOMS'], isAdvanced: true },
  { name: '✨ 신비로운 칠지도', description: '왕의 권위가 서린 신비로운 검. 월급이 20% 증가합니다.', effect: 'SALARY_BONUS_20', icon: '⚔️', dynasty: ['GOJOSEON_THREE_KINGDOMS'], isAdvanced: true },
  { name: '✨ 삼한의 맹약', description: '국가 주도의 정밀한 토지 정책으로, 모든 도시 구매 비용을 20% 할인받습니다.', effect: 'LAND_PURCHASE_DISCOUNT_20', icon: '📝', dynasty: ['GOJOSEON_THREE_KINGDOMS'], isAdvanced: true },

  // UNIFIED_SILLA_BALHAE
  { name: '✨ 영롱한 만파식적', description: '세상의 모든 분쟁을 잠재우는 성스러운 피리. 모든 통행료 수입이 20% 증가합니다.', effect: 'TOLL_INCREASE_20', icon: '🎍', dynasty: ['UNIFIED_SILLA_BALHAE'], isAdvanced: true },
  { name: '✨ 황금 주령구', description: '왕의 놀이 기구. 벌칙 대신 큰 행운을 가져와 상대에게 지불하는 모든 통행료가 20% 감소합니다.', effect: 'TOLL_DISCOUNT_20', icon: '🎲', dynasty: ['UNIFIED_SILLA_BALHAE'], isAdvanced: true },
  { name: '✨ 발해의 최고급 담비 가죽', description: '황제에게 진상되던 귀한 특산품. 막대한 무역 이익으로 월급이 20% 증가합니다.', effect: 'SALARY_BONUS_20', icon: '🐾', dynasty: ['UNIFIED_SILLA_BALHAE'], isAdvanced: true },
  { name: '✨ 왕토 사상', description: '국가 주도의 정밀한 토지 정책으로, 모든 도시 구매 비용을 20% 할인받습니다.', effect: 'LAND_PURCHASE_DISCOUNT_20', icon: '📝', dynasty: ['UNIFIED_SILLA_BALHAE'], isAdvanced: true },

  // LATER_THREE_KINGDOMS
  { name: '✨ 궁예의 관심법', description: '궁예의 궁극의 능력. 상대의 모든 것을 꿰뚫어보아 통행료 수입을 20% 증가시킵니다.', effect: 'TOLL_INCREASE_20', icon: '👁️', dynasty: ['LATER_THREE_KINGDOMS'], isAdvanced: true },
  { name: '✨ 견훤의 탁월한 외교술', description: '황제를 감동시킨 외교술. 상대에게 지불하는 통행료가 20% 감소합니다.', effect: 'TOLL_DISCOUNT_20', icon: '✉️', dynasty: ['LATER_THREE_KINGDOMS'], isAdvanced: true },
  { name: '✨ 해상 대왕국의 꿈', description: '왕건의 거대 해상 세력이 모든 교역로를 장악하여 월급이 20% 증가합니다.', effect: 'SALARY_BONUS_20', icon: '⚓', dynasty: ['LATER_THREE_KINGDOMS'], isAdvanced: true },
  { name: '✨ 역분전 지급 문서', description: '국가 주도의 정밀한 토지 정책으로, 모든 도시 구매 비용을 20% 할인받습니다.', effect: 'LAND_PURCHASE_DISCOUNT_20', icon: '📝', dynasty: ['LATER_THREE_KINGDOMS'], isAdvanced: true },

  // GORYEO
  { name: '✨ 고려 비색 상감청자', description: '고려 예술의 결정체. 그 가치를 알아본 방문객들이 통행료를 20% 더 냅니다.', effect: 'TOLL_INCREASE_20', icon: '🏺', dynasty: ['GORYEO'], isAdvanced: true },
  { name: '✨ 대무역상의 협상술', description: '벽란도 거상(巨商)의 기술. 통행료 지불 시 20%를 할인받습니다.', effect: 'TOLL_DISCOUNT_20', icon: '🚢', dynasty: ['GORYEO'], isAdvanced: true },
  { name: '✨ 천년 묵은 고려 인삼', description: '불로장생의 명약. 막대한 수출 수익으로 월급이 20% 증가합니다.', effect: 'SALARY_BONUS_20', icon: '🌿', dynasty: ['GORYEO'], isAdvanced: true },
  { name: '✨ 전시과 문서', description: '국가 주도의 정밀한 토지 정책으로, 모든 도시 구매 비용을 20% 할인받습니다.', effect: 'LAND_PURCHASE_DISCOUNT_20', icon: '📝', dynasty: ['GORYEO'], isAdvanced: true },

  // JOSEON
  { name: '✨ 훈민정음 원본', description: '세종대왕의 애민정신이 담긴 원본. 모든 땅의 통행료 수입이 20% 증가합니다.', effect: 'TOLL_INCREASE_20', icon: '✍️', dynasty: ['JOSEON'], isAdvanced: true },
  { name: '✨ 정약용의 거중기', description: '수원 화성을 건설한 기술력. 통행료 지불액을 20% 감소시킵니다.', effect: 'TOLL_DISCOUNT_20', icon: '🏗️', dynasty: ['JOSEON'], isAdvanced: true },
  { name: '✨ 세종의 앙부일구', description: '조선 최고의 과학 기술력. 시간의 흐름을 정확히 읽어 월급이 20% 증가합니다.', effect: 'SALARY_BONUS_20', icon: '☀️', dynasty: ['JOSEON'], isAdvanced: true },
  { name: '✨ 양전 사업 문서', description: '국가 주도의 정밀한 토지 정책으로, 모든 도시 구매 비용을 20% 할인받습니다.', effect: 'LAND_PURCHASE_DISCOUNT_20', icon: '📝', dynasty: ['JOSEON'], isAdvanced: true },

  // MODERN_CONTEMPORARY
  { name: '✨ IMF 금모으기 운동 증서', description: '전국민의 염원이 담긴 증서. 통행료 수입이 20% 증가합니다.', effect: 'TOLL_INCREASE_20', icon: '🏅', dynasty: ['MODERN_CONTEMPORARY'], isAdvanced: true },
  { name: '✨ 88올림픽 황금 호돌이', description: '세계 평화의 상징. 우호적인 분위기 속에서 통행료를 20% 할인받습니다.', effect: 'TOLL_DISCOUNT_20', icon: '🐯', dynasty: ['MODERN_CONTEMPORARY'], isAdvanced: true },
  { name: '✨ 빌보드 1위 K-POP 앨범', description: '전 세계를 제패한 한류의 힘. 막대한 저작권 수입으로 월급이 20% 증가합니다.', effect: 'SALARY_BONUS_20', icon: '🎤', dynasty: ['MODERN_CONTEMPORARY'], isAdvanced: true },
  { name: '✨ 경제개발계획서', description: '국가 주도의 정밀한 토지 정책으로, 모든 도시 구매 비용을 20% 할인받습니다.', effect: 'LAND_PURCHASE_DISCOUNT_20', icon: '📝', dynasty: ['MODERN_CONTEMPORARY'], isAdvanced: true },
];

const createCenterImage = (icons: string[]) => {
    const positions = [
        { x: 40, y: 70, rotate: -10 },
        { x: 150, y: 50, rotate: 10 },
        { x: 250, y: 100, rotate: 5 },
        { x: 50, y: 250, rotate: 5 },
        { x: 220, y: 220, rotate: -15 },
        { x: 130, y: 160, rotate: -5 },
    ];
    const texts = icons.map((icon, i) => {
        const p = positions[i % positions.length];
        return `<text x='${p.x}' y='${p.y}' transform='rotate(${p.rotate}, ${p.x+30}, ${p.y})'>${icon}</text>`;
    }).join('');

    const svg = `
        <svg xmlns='http://www.w3.org/2000/svg' width='300' height='300'>
            <style>text { font-size: 60px; font-family: sans-serif; opacity: 0.15; }</style>
            ${texts}
        </svg>
    `;
    return `data:image/svg+xml,${encodeURIComponent(svg)}`;
};


export const DYNASTY_BOARD_CENTER_IMAGES: Record<Dynasty, string> = {
    GOJOSEON_THREE_KINGDOMS: createCenterImage(['🌳', '🗡️', '🏹', '👑', '🛡️', '🥚']),
    UNIFIED_SILLA_BALHAE: createCenterImage(['🌇', '🛕', '🔔', '🌊', '👑', '🐴']),
    LATER_THREE_KINGDOMS: createCenterImage(['👑', '🏯', '⚔️', '🌊', '🛡️', '🏆']),
    GORYEO: createCenterImage(['👑', '🏯', '🗣️', '⚔️', '🏺', '📖']),
    JOSEON: createCenterImage(['👑', '🏛️', '✍️', '🔬', '🛡️', '🐢']),
    MODERN_CONTEMPORARY: createCenterImage(['🇰🇷', '🏢', '🗳️', '🎤', '📱', '🕊️']),
};

// FIX: Export SOUNDS to be used across components.
export const SOUNDS = {
    DICE_ROLL: 'https://actions.google.com/sounds/v1/games/dice_roll_for_board_game_with_cup.ogg',
    PAY_TOLL: 'https://actions.google.com/sounds/v1/cartoon/cash_register.ogg',
    BUY_CITY: 'https://actions.google.com/sounds/v1/cartoon/magic_chime.ogg',
    EVENT_CARD: 'https://actions.google.com/sounds/v1/magical/magic_spell_charge_up.ogg',
    SALARY: 'https://actions.google.com/sounds/v1/coins/clinking_coins.ogg',
    MOVE_PAWN: 'https://actions.google.com/sounds/v1/impacts/wood_thump.ogg',
    ITEM_ACQUIRE: 'https://actions.google.com/sounds/v1/magical/magic_wand_spell.ogg'
};

// FIX: Export board template and city pools for dynamic board generation.
export const TEMPLATE_BOARD_STRUCTURE: BoardSpace[] = [
    { name: '🏁 출발!', type: 'start', description: "천하를 향한 위대한 여정을 시작합니다! 한 바퀴를 돌아 이곳을 지날 때마다 **200골드**를 받습니다. 이 자금은 당신의 세력을 키우는 데 중요한 밑거름이 될 것입니다. 전략적으로 활용하여 경쟁자들을 앞서나가세요." },
    { name: 'City', type: 'city', price: 60 },
    { name: 'City', type: 'city', price: 70 },
    { name: 'City', type: 'city', price: 80 },
    { name: '📜 역사 카드', type: 'event' },
    { name: '🏺 아이템', type: 'item', description: '이 칸에 도착하면 해당 시대의 특별한 유물 아이템을 얻습니다. 아이템은 지속적인 효과를 부여합니다.', icon: '🏺' },
    { name: 'City', type: 'city', price: 90 },
    { name: 'City', type: 'city', price: 100 },
    { name: 'City', type: 'city', price: 110 },
    { name: 'City', type: 'city', price: 120 },
    
    { name: '🏝️ 무인도', type: 'corner', description: "고요한 섬에서 잠시 세상사를 잊고 휴식을 취합니다. **3턴** 동안 휴식하며, 주사위 **더블**이 나오면 즉시 탈출할 수 있습니다. 위대한 여정 중 잠시 쉬어가는 것도 현명한 전략일 수 있습니다. 재충전의 시간을 가지세요." },
    { name: 'City', type: 'city', price: 140 },
    { name: 'City', type: 'city', price: 150 },
    { name: '📜 역사 카드', type: 'event' },
    { name: 'City', type: 'city', price: 160 },
    { name: '🏺 아이템', type: 'item', description: '이 칸에 도착하면 해당 시대의 특별한 유물 아이템을 얻습니다. 아이템은 지속적인 효과를 부여합니다.', icon: '🏺' },
    { name: 'City', type: 'city', price: 180 },
    { name: 'City', type: 'city', price: 200 },
    { name: 'City', type: 'city', price: 210 },
    { name: 'City', type: 'city', price: 220 },

    { name: '🚀 순간이동', type: 'travel', description: "원하는 곳 어디든 이동할 수 있습니다! 출발지를 지나가면 월급도 받아요. 전략적으로 중요한 위치로 이동하여 **기회를 잡거나 위기를 벗어날 수 있는** 절호의 찬스입니다. 신중하게 목적지를 선택하세요." },
    { name: 'City', type: 'city', price: 240 },
    { name: 'City', type: 'city', price: 250 },
    { name: '📜 역사 카드', type: 'event' },
    { name: 'City', type: 'city', price: 260 },
    { name: '🏺 아이템', type: 'item', description: '이 칸에 도착하면 해당 시대의 특별한 유물 아이템을 얻습니다. 아이템은 지속적인 효과를 부여합니다.', icon: '🏺' },
    { name: 'City', type: 'city', price: 280 },
    { name: 'City', type: 'city', price: 300 },
    { name: 'City', type: 'city', price: 310 },
    { name: 'City', type: 'city', price: 320 },
    
    { name: '💰 국고', type: 'treasury', description: "**홀수 번째**로 도착하면 세금을 납부하고, **짝수 번째**로 도착하면 쌓인 국고를 모두 가져갑니다! 초기 세금은 80골드이며, 낼 때마다 50%씩 증가합니다. 국운이 당신에게 미소 짓기를!", icon: '💰' },
    { name: 'City', type: 'city', price: 340 },
    { name: '📜 역사 카드', type: 'event' },
    { name: 'City', type: 'city', price: 350 },
    { name: '🏺 아이템', type: 'item', description: '이 칸에 도착하면 해당 시대의 특별한 유물 아이템을 얻습니다. 아이템은 지속적인 효과를 부여합니다.', icon: '🏺' },
    { name: 'City', type: 'city', price: 380 },
    { name: 'City', type: 'city', price: 420 },
    { name: 'City', type: 'city', price: 450 },
    { name: 'City', type: 'city', price: 500 },
    { name: 'City', type: 'city', price: 520 },
];

type CityPoolItem = Omit<BoardSpace, 'price' | 'owner' | 'multiplier'>;

export const DYNASTY_CITY_POOLS: Record<Dynasty, CityPoolItem[]> = {
    GOJOSEON_THREE_KINGDOMS: [
        { name: '🌳 신단수', type: 'city', category: '장소', description: "환웅이 하늘에서 내려와 인간 세상을 다스리기 시작한 성스러운 나무입니다. 이곳에서 곰과 호랑이가 사람이 되게 해달라고 빌었고, 쑥과 마늘을 먹고 견딘 곰이 **웅녀**가 되어 환웅과 혼인하여 **단군**을 낳았다는 이야기가 전해집니다. 우리 민족의 시작을 알리는 신화적인 장소입니다.", icon: '🌳' },
        { name: '🏰 왕검성', type: 'city', category: '장소', description: "고조선의 수도로, 대동강 유역에 위치했던 것으로 추정됩니다. **단군왕검**이 세운 이 도시는 고조선의 정치, 경제, 문화의 중심지였으며, 강력한 국가의 상징이었습니다. 훗날 **위만조선**의 수도가 되기도 했습니다.", icon: '🏰' },
        { name: '⚖️ 8조법', type: 'city', category: '제도', description: "고조선 사회의 질서를 유지했던 8개의 법 조항입니다. '**사람을 죽인 자는 사형에 처한다**', '**남에게 상처를 입힌 자는 곡식으로 갚는다**' 등 간단하지만 강력한 법으로 백성들의 생명과 재산을 보호했습니다. 이를 통해 당시 사회상을 엿볼 수 있습니다.", icon: '⚖️' },
        { name: '🗡️ 비파형동검', type: 'city', category: '유물', description: "고조선을 대표하는 청동기 유물로, 악기 **비파**를 닮아 이런 이름이 붙었습니다. 주로 지배층의 무덤에서 발견되며, 당시 지배자의 강력한 권위와 군사력을 상징하는 중요한 유물입니다. 이는 고조선의 영토 범위를 알려주는 지표가 되기도 합니다.", icon: '🗡️' },
        { name: '🏹 주몽', type: 'city', category: '인물', description: "활을 잘 쏘는 자, **주몽**! 부여에서 뛰어난 활솜씨 때문에 시기를 받아 남쪽으로 내려와 **고구려**를 건국했습니다. 그의 이야기는 고구려 건국의 신성함과 정당성을 보여주는 중요한 신화이며, 어려움을 극복하는 영웅의 모습을 보여줍니다.", icon: '🏹' },
        { name: '🏯 국내성', type: 'city', category: '장소', description: "고구려의 두 번째 수도로, 약 **425년간** 고구려의 중심지 역할을 했습니다. 산으로 둘러싸인 방어에 유리한 지형에 자리 잡아, 고구려가 강력한 대제국으로 성장하는 발판이 되었습니다. 광개토대왕릉비가 이곳 근처에 있습니다.", icon: '🏯' },
        { name: '👑 연개소문', type: 'city', category: '인물', description: "고구려 말기의 강력한 **대막리지**(최고 관직)였습니다. 당나라의 거대한 군대에 맞서 싸우며 고구려의 자주성을 지키려 했던 불굴의 의지를 상징하는 인물입니다. 그의 강력한 리더십은 고구려의 마지막 불꽃이었지만, 그의 죽음 이후 고구려는 급격히 쇠퇴합니다.", icon: '👑' },
        { name: '🏞️ 광개토대왕릉', type: 'city', category: '장소', description: "만주를 호령한 정복군주, **광개토대왕**의 기상이 느껴지는 거대한 무덤입니다. 무덤 옆에 세워진 **광개토대왕릉비**에는 그의 위대한 정복 활동과 업적이 새겨져 있어, 고구려의 강성했던 역사를 생생하게 증언하고 있습니다. 이는 우리 역사상 가장 큰 비석 중 하나입니다.", icon: '🏞️' },
        { name: '🎨 수산리 고분벽화', type: 'city', category: '문화', description: "고구려 귀족의 생활 모습을 생생하게 보여주는 벽화입니다. 화려한 옷을 입은 귀족 부부가 시종들과 함께 나들이하는 모습이 담겨 있어, 당시의 복식, 건축, 생활 문화를 생생하게 엿볼 수 있는 귀중한 자료입니다. **고구려 회화**의 높은 수준을 보여줍니다.", icon: '🎨' },
        { name: '⚔️ 살수', type: 'city', category: '전투', description: "**을지문덕** 장군이 수나라 100만 대군을 물리친 **살수대첩**의 현장입니다. 강물을 막았다가 한꺼번에 터뜨리는 지략으로 수나라 군대를 거의 전멸시켜, 우리 역사상 가장 위대한 승리 중 하나로 기록되었습니다. 이 승리로 고구려는 수나라의 침략을 막아냈습니다.", icon: '⚔️' },
        { name: '🧱 안시성', type: 'city', category: '장소', description: "당나라 대군을 물리친 철옹성의 상징입니다. 수십만 대군에 맞서 성주와 백성들이 하나 되어 싸워 나라를 지켜냈습니다. 이 전투는 **고구려인의 강인한 정신력**과 단결력을 보여주는 대표적인 사례이며, 영화로도 만들어졌습니다.", icon: '🧱' },
        { name: '👑 온조왕', type: 'city', category: '인물', description: "주몽의 아들로, 형 비류와 함께 남쪽으로 내려와 비옥한 **한강 유역**에 **백제**를 건국했습니다. 온조왕의 결정은 백제가 삼국 중 가장 먼저 전성기를 맞이하는 기틀을 마련했습니다. 그는 백제의 시조로 추앙받습니다.", icon: '👑' },
        { name: '🛡️ 계백 장군', type: 'city', category: '인물', description: "**황산벌**에서 **5천 결사대**를 이끌고 신라 5만 대군에 맞서 싸운 비운의 영웅입니다. 나라의 운명이 걸린 전투에서 수적으로 불리함에도 불구하고 끝까지 맞서 싸워, 백제의 마지막 충절과 용맹을 보여주었습니다.", icon: '🛡️' },
        { name: '🏺 금동대향로', type: 'city', category: '유물', description: "**백제 예술의 정수**. 신선들이 사는 이상 세계를 정교하고 아름답게 표현한 향로입니다. 용이 향로를 받치고, 봉황이 뚜껑을 장식하는 등, 당시 백제인들의 뛰어난 상상력과 금속 공예 기술을 보여주는 **국보급 유물**입니다.", icon: '🏺' },
        { name: '🥚 박혁거세', type: 'city', category: '인물', description: "알에서 태어난 **신라의 시조**입니다. 나정이라는 우물가에서 발견된 커다란 박 모양의 알에서 태어났다고 전해지며, 6부 촌장들의 추대를 받아 왕이 되었습니다. 그의 탄생 신화는 **신라 건국의 신비로움**을 더해줍니다.", icon: '🥚' },
        { name: '🔭 첨성대', type: 'city', category: '문화', description: "**선덕여왕** 때 만들어진 동양에서 가장 오래된 천문 관측대입니다. 하늘의 움직임을 관찰하여 농사 시기를 정하고 국가의 길흉을 점치는 등, 과학과 정치가 결합된 신라의 뛰어난 건축물입니다. **유네스코 세계문화유산**에 등재될 가치가 충분합니다.", icon: '🔭' },
        { name: '⚔️ 화랑도', type: 'city', category: '제도', description: "신라의 청소년 인재 양성 제도로, 학문과 무예를 함께 가르쳤습니다. 화랑들은 '**세속오계**'라는 행동 규범을 따르며 심신을 단련했고, 훗날 **삼국 통일의 가장 큰 원동력**이 되었습니다. 김유신 장군도 화랑 출신입니다.", icon: '⚔️' },
        { name: '🌇 경주', type: 'city', category: '장소', description: "천 년 동안 신라의 수도였던 도시로, 도시 전체가 유적지라 '**지붕 없는 박물관**'이라 불립니다. 불국사, 석굴암, 첨성대 등 수많은 문화유산을 품고 있는 신라의 심장이었습니다. **유네스코 세계문화유산**으로 지정된 곳이 많습니다.", icon: '🌇' },
        { name: '🗡️ 김유신 장군', type: 'city', category: '인물', description: "화랑 출신의 명장으로, **삼국 통일의 위업**을 달성한 일등공신입니다. 뛰어난 군사 전략과 리더십으로 수많은 전투를 승리로 이끌었으며, **무열왕과 문무왕**을 도와 통일의 대업을 완성했습니다.", icon: '🗡️' },
        { name: '🤝 나당연합군', type: 'city', category: '전투', description: "신라와 당나라가 백제와 고구려를 공격하기 위해 결성한 동맹입니다. 이 연합은 삼국 통일을 앞당겼지만, 이후 **당나라의 야욕**에 맞서 싸워야 하는 새로운 과제를 안겨주기도 했습니다. 전략적인 선택이었지만, 그 대가도 있었습니다.", icon: '🤝' },
        { name: '🛕 불국사', type: 'city', category: '문화', description: "신라 불교 예술의 정수로, '**부처님의 나라**'를 지상에 완벽하게 구현한 사찰입니다. **석가탑과 다보탑**, 청운교와 백운교 등 완벽한 균형미와 정교한 건축 기술로 세계적인 가치를 인정받았습니다. **유네스코 세계문화유산**입니다.", icon: '🛕' },
        { name: '👑 선덕여왕', type: 'city', category: '인물', description: "신라 최초의 여왕으로, 지혜와 통찰력으로 나라를 다스렸습니다. **첨성대**를 세워 농업 발전에 기여하고, 분황사와 **황룡사 9층 목탑**을 건립하는 등 문화적으로도 큰 업적을 남겼습니다. 그녀의 리더십은 오늘날에도 높이 평가받습니다.", icon: '👑' },
        { name: '🌊 장보고', type: 'city', category: '인물', description: "완도에 **청해진**을 설치하여 해적을 소탕하고 동아시아 해상 무역을 장악한 '**바다의 왕**'입니다. 그의 활약으로 신라는 당나라, 일본과 활발히 교류하며 국제 무역의 중심지로 떠올랐습니다. 그의 이야기는 드라마로도 제작되었습니다.", icon: '🌊' },
        { name: '⚔️ 삼국통일', type: 'city', category: '사건', description: "고구려, 백제, 신라로 나뉘었던 한반도를 하나로 합친 위대한 업적입니다. 이로써 **한민족의 정체성**이 형성되는 중요한 기틀이 마련되었으며, 이는 우리 역사에 큰 전환점이 되었습니다. 하지만 **대동강 이남**의 불완전한 통일이라는 한계도 지적됩니다.", icon: '⚔️' },
        { name: '🏞️ 포석정', type: 'city', category: '장소', description: "흐르는 물에 술잔을 띄우고 시를 읊던 신라 귀족들의 연회 장소였습니다. 하지만 927년, 후백제 **견훤**의 침입으로 경애왕이 최후를 맞이한 비극의 장소이기도 하여 **신라 멸망의 상징**처럼 여겨집니다.", icon: '🏞️' },
        { name: '🐲 문무대왕릉', type: 'city', category: '장소', description: "'**죽어서도 용이 되어 나라를 지키겠다**'는 유언에 따라 동해 바다에 만들어진 세계 유일의 **수중릉**입니다. 삼국 통일을 완성한 문무왕의 애국심과 호국 정신을 느낄 수 있는 성스러운 장소입니다.", icon: '🐲' },
        { name: '💎 금관', type: 'city', category: '유물', description: '신라의 황금 유물을 대표하는 **금관**. 화려하고 정교한 세공 기술을 보여줍니다. 나뭇가지와 사슴뿔 모양의 장식은 하늘과 땅을 연결하는 **샤먼으로서의 왕의 권위**를 상징하며, 신라의 독특한 문화를 보여줍니다.', icon: '💎' },
        { name: '🎨 사신도', type: 'city', category: '문화', description: '고구려 고분 벽화의 정수. **청룡, 백호, 주작, 현무**가 동서남북 사방을 지키는 모습을 그렸습니다. 이는 무덤의 주인을 사후 세계에서도 보호하려는 고구려인의 내세관과 세계관을 힘찬 필치로 보여주는 위대한 예술 작품입니다.', icon: '🎨' },
        { name: '🌾 부여', type: 'city', category: '장소', description: "만주 지역을 중심으로 성장한 고대 국가. 고구려와 백제의 건국 세력이 이곳에서 나왔습니다. **1책 12법**이라는 엄격한 법이 있었으며, 하늘에 제사를 지내는 '**영고**'라는 풍습이 있었습니다.", icon: '🌾' },
        { name: '🦀 옥저와 동예', type: 'city', category: '장소', description: "함경도와 강원도 북부 동해안에 위치했던 나라들. **해산물이 풍부**했지만 고구려의 압박을 받았습니다. 동예에는 다른 부족의 영역을 침범하면 소나 말로 변상하는 '**책화**'라는 제도가 있었습니다.", icon: '🦀' },
        { name: '🤝 삼한', type: 'city', category: '장소', description: "한반도 남부에 위치했던 **마한, 진한, 변한**을 일컫는 말입니다. 이 중 마한의 **목지국**이 삼한 전체를 이끌었으며, 변한 지역은 철이 많이 생산되어 교역이 활발했습니다. 훗날 백제, 신라, 가야로 발전합니다.", icon: '🤝' },
        { name: '📖 진대법', type: 'city', category: '제도', description: "고구려 **고국천왕** 때 재상 **을파소**의 건의로 시행된 빈민 구제 제도입니다. 봄에 곡식을 빌려주고 가을에 갚게 하여, 굶주리는 백성을 구제하고 국가의 안정을 꾀했습니다.", icon: '📖' },
        { name: '👑 근초고왕', type: 'city', category: '인물', description: "백제의 최전성기를 이끈 왕. 남쪽으로 마한을 정복하고, 북쪽으로 고구려의 평양성을 공격하여 **고국원왕**을 전사시키는 등 활발한 정복 활동으로 백제의 영토를 크게 넓혔습니다.", icon: '👑' },
        { name: '🏰 위례성', type: 'city', category: '장소', description: "백제의 첫 수도로, 비옥한 **한강 유역**에 위치하여 백제가 강국으로 성장하는 기반이 되었습니다. 풍납토성과 몽촌토성이 그 유적으로 추정되며, 초기 백제의 중심지였습니다.", icon: '🏰' },
        { name: '🎶 서동요', type: 'city', category: '문화', description: "백제 **무왕**이 어린 시절 신라의 선화 공주와 결혼하기 위해 퍼뜨렸다는 향가. '선화 공주님은 남몰래 시집가서, 밤에 몰래 서동을 안고 간다'는 내용으로, 아이들을 통해 소문을 퍼뜨린 지혜를 엿볼 수 있습니다.", icon: '🎶' },
        { name: '👑 지증왕', type: 'city', category: '인물', description: "신라의 국호를 '사라'에서 '**신라**'로 확정하고, 왕의 칭호를 '마립간'에서 '**왕**'으로 바꾼 군주입니다. **우산국(울릉도)**을 정복하고, 소를 이용한 깊이갈이(우경)를 장려하는 등 국가 체제를 정비했습니다.", icon: '👑' },
        { name: '🦁 이사부', type: 'city', category: '인물', description: "신라의 명장. 나무로 만든 사자를 이용해 **우산국(울릉도)**을 정복했으며, 훗날 **대가야**를 정복하여 신라의 영토를 크게 넓혔습니다. 그의 활약은 신라가 삼국 통일의 기반을 닦는 데 큰 도움이 되었습니다.", icon: '🦁' },
        { name: '💰 김수로왕', type: 'city', category: '인물', description: "하늘에서 내려온 6개의 알 중 가장 먼저 깨어나 **금관가야**를 건국한 시조입니다. 인도 아유타국 공주 **허황옥**과 결혼했다는 신비로운 이야기가 전해지며, 김해 김씨의 시조이기도 합니다.", icon: '💰' },
        { name: '🏰 사비성', type: 'city', category: '장소', description: "백제가 **성왕** 때 웅진(공주)에서 사비(부여)로 옮긴 마지막 수도입니다. 계획적으로 조성된 도시로, **정림사지 5층 석탑** 등 백제 후기 문화의 정수를 보여주는 유적이 많이 남아있습니다.", icon: '🏰' },
        { name: '👑 진흥왕', type: 'city', category: '인물', description: "신라의 전성기를 이끈 정복군주. **화랑도**를 국가 조직으로 개편하고, 백제와 연합하여 한강 유역을 차지한 뒤 백제를 배신하고 한강 전체를 독차지했습니다. **순수비**를 세워 자신의 업적을 과시했습니다.", icon: '👑' },
        { name: '⚔️ 관산성 전투', type: 'city', category: '전투', description: "신라에 빼앗긴 한강 유역을 되찾기 위해 백제 **성왕**이 신라를 공격했다가 전사한 비극적인 전투입니다. 이 전투의 패배로 백제는 중흥의 꿈이 꺾이고, 신라는 삼국 통일의 주도권을 잡게 되었습니다.", icon: '⚔️' },
        { name: '🧱 임신서기석', type: 'city', category: '유물', description: "신라의 두 화랑이 나라에 대한 충성을 맹세하며 그 내용을 새긴 비석. '**하늘 앞에 맹세한다. 지금부터 3년 뒤까지 충도를 집지하고...**'라는 내용으로, 화랑들의 유교 경전 학습과 충성심을 보여줍니다.", icon: '🧱' },
        { name: '👑 법흥왕', type: 'city', category: '인물', description: "**율령 반포, 골품제 정비, 불교 공인** 등을 통해 신라의 중앙 집권 국가 체제를 완성한 왕입니다. **이차돈의 순교**를 계기로 불교를 국가 종교로 받아들여 백성의 사상을 통합했습니다.", icon: '🥚' },
        { name: '🙏 이차돈', type: 'city', category: '인물', description: "신라의 불교 공인을 위해 자신의 목숨을 바친 순교자. 귀족들의 반대에도 불구하고, 그의 목을 베자 **흰 피**가 솟아오르고 하늘에서는 꽃비가 내렸다는 이야기가 전해집니다. 이를 계기로 신라는 불교를 공인하게 되었습니다.", icon: '🙏' },
        { name: '📖 역사서 편찬', type: 'city', category: '사건', description: "삼국은 각국의 정통성을 내세우고 왕실의 권위를 높이기 위해 역사서를 편찬했습니다. 백제의 **서기**, 고구려의 **신집**, 신라의 **국사**가 있었으나, 안타깝게도 현재 전해지지는 않습니다.", icon: '📖' },
        { name: '👑 장수왕', type: 'city', category: '인물', description: "광개토대왕의 아들로, 수도를 국내성에서 **평양**으로 옮기는 **남하 정책**을 추진하여 고구려의 최전성기를 이끌었습니다. 백제의 수도 한성을 함락시키고 **개로왕**을 죽여 백제를 큰 위기에 빠뜨렸습니다.", icon: '👑' },
        { name: '🪨 중원고구려비', type: 'city', category: '유물', description: "장수왕이 남한강 유역까지 진출했음을 증명하는 비석. 현재 **충주**에 있으며, 한반도에 유일하게 남아있는 고구려비입니다. 고구려가 신라를 '**동이(東夷)**'라 부르며 영향력을 행사했음을 보여줍니다.", icon: '🪨' },
        { name: '🤝 나제동맹', type: 'city', category: '전투', description: "고구려의 남하 정책에 맞서기 위해 신라와 백제가 맺은 군사 동맹. 약 120년간 유지되며 고구려의 공격을 막아내는 데 기여했지만, **진흥왕의 배신**으로 깨지고 맙니다.", icon: '🤝' },
        { name: '🕊️ 의자왕', type: 'city', category: '인물', description: "백제의 마지막 왕. 즉위 초에는 신라를 공격하며 영토를 회복하는 등 유능한 군주였으나, 점차 향락에 빠져 정치를 돌보지 않아 결국 나라를 멸망에 이르게 했습니다. '**해동증자**'라 불릴 만큼 효심이 깊었다고도 합니다.", icon: '🕊️' },
        { name: '👑 무령왕', type: 'city', category: '인물', description: "혼란에 빠진 백제를 안정시키고 중흥의 기틀을 마련한 왕. 지방에 **22담로**를 설치하여 왕족을 파견하고 지방 통제를 강화했습니다. 그의 무덤인 **무령왕릉**은 도굴되지 않은 채 발견되어 백제사 연구에 귀중한 자료를 제공했습니다.", icon: '👑' },
        { name: '🧱 무령왕릉', type: 'city', category: '장소', description: "백제 25대 무령왕의 무덤. 도굴되지 않은 채 완벽한 상태로 발견되어 세상을 놀라게 했습니다. **중국 남조의 영향**을 받은 벽돌무덤 양식으로, 당시 백제의 활발한 국제 교류를 보여주는 중요한 유적입니다.", icon: '🧱' },
        { name: '🤝 백제부흥운동', type: 'city', category: '사건', description: "백제 멸망 후, **흑치상지, 복신, 도침** 등이 왕자 부여풍을 왕으로 추대하고 나당연합군에 맞서 싸운 운동입니다. **백강 전투**에서 패배하며 실패로 끝났지만, 백제 유민들의 꺾이지 않는 저항 정신을 보여줍니다.", icon: '🤝' },
        { name: '🗡️ 을지문덕', type: 'city', category: '인물', description: "수나라의 100만 대군을 **살수대첩**에서 물리친 고구려의 위대한 명장. 거짓 항복과 '**여수장우중문시**'라는 시를 통해 적을 교란시키는 등 뛰어난 지략으로 나라를 구했습니다.", icon: '🗡️' },
        { name: '⚔️ 황산벌 전투', type: 'city', category: '전투', description: "백제 멸망의 마지막 길목에서 **계백 장군**이 이끄는 5천 결사대가 신라 5만 대군에 맞서 싸운 비장한 전투. 수적 열세에도 불구하고 용감히 싸웠으나, 결국 패배하여 백제는 멸망의 길을 걷게 됩니다.", icon: '⚔️' },
        { name: '👑 김춘추', type: 'city', category: '인물', description: "신라의 외교가이자 훗날 **태종무열왕**. 백제의 공격으로 위기에 처한 신라를 구하기 위해 고구려와 당나라를 오가며 외교 활동을 펼쳐 결국 **나당 동맹**을 성사시켰습니다. 삼국 통일의 기틀을 마련한 인물입니다.", icon: '👑' },
        { name: '🐎 천마도', type: 'city', category: '문화', description: "신라의 고분 **천마총**에서 발견된 말다래(흙받이). 자작나무 껍질에 하늘을 나는 신비로운 흰말을 그렸습니다. 이는 신라의 뛰어난 회화 수준과 사후 세계에 대한 신라인의 믿음을 보여주는 귀중한 유물입니다.", icon: '🐎' },
    ],
    UNIFIED_SILLA_BALHAE: [
        { name: '🌇 경주', type: 'city', category: '장소', description: "통일신라의 수도로, 국제적인 도시로 번성했습니다. **실크로드**를 통해 들어온 서역의 문물로 가득 찼으며, 인구가 100만에 육박하는 세계적인 대도시였습니다. 밤늦도록 불이 꺼지지 않는다는 의미에서 '**야화**'라 불리기도 했습니다.", icon: '🌇' },
        { name: '🏞️ 동궁과 월지', type: 'city', category: '장소', description: "과거 '**안압지**'로 불렸던 신라 왕궁의 별궁 터입니다. 나라의 경사가 있을 때 연회를 베풀던 곳으로, 밤의 경치가 특히 아름다워 신라 귀족들의 화려한 생활을 엿볼 수 있습니다. 이곳에서 발견된 **주령구**는 당시 사람들의 놀이 문화를 보여줍니다.", icon: '🏞️' },
        { name: '🛕 불국사&석굴암', type: 'city', category: '문화', description: "**김대성**의 발원으로 만들어진 신라 불교 예술의 최고 걸작입니다. 불국사는 부처의 나라를, 석굴암은 완벽한 깨달음의 세계를 상징하며, **유네스코 세계문화유산**으로 지정되어 그 가치를 세계적으로 인정받고 있습니다.", icon: '🛕' },
        { name: '🔔 성덕대왕신종', type: 'city', category: '유물', description: "'**에밀레종**'이라는 슬픈 전설을 간직한, 세계에서 가장 아름다운 소리를 내는 종입니다. 길고 은은한 울림은 통일신라의 뛰어난 주조 기술을 보여주는 증거이며, **국보 제29호**로 지정되어 있습니다.", icon: '🔔' },
        { name: '✍️ 이두', type: 'city', category: '문화', description: "신라 시대에 한자의 음과 뜻을 빌려 우리말을 표기하던 방식입니다. **설총**이 집대성했으며, **훈민정음** 창제 이전까지 우리말을 기록하는 중요한 역할을 했습니다. 신라 지식인들의 지혜를 엿볼 수 있습니다.", icon: '✍️' },
        { name: '🤝 9서당 10정', type: 'city', category: '제도', description: "통일신라의 중앙군과 지방군 체제. 고구려, 백제, 말갈인까지 포함하여 구성함으로써 **민족 융합**을 꾀했던 선진적인 군사 제도였습니다. 이는 통일 이후 사회 안정을 이루는 데 큰 기여를 했습니다.", icon: '🤝' },
        { name: '👑 신문왕', type: 'city', category: '인물', description: "통일신라의 전성기를 이끈 강력한 왕. **김흠돌의 난**을 진압하여 귀족 세력을 숙청하고 왕권을 강화했습니다. **국학**을 설립하여 유학을 교육하고, **관료전 지급, 녹읍 폐지** 등 개혁 정치를 펼쳤습니다.", icon: '👑' },
        { name: '🌊 장보고', type: 'city', category: '인물', description: "완도에 **청해진**을 설치하여 해적을 소탕하고 동아시아 해상 무역을 장악한 '**바다의 왕**'입니다. 그의 활약으로 신라는 당나라, 일본과 활발히 교류하며 국제 무역의 중심지로 떠올랐습니다. 그의 이야기는 드라마로도 제작되었습니다.", icon: '🌊' },
        { name: '📖 왕오천축국전', type: 'city', category: '유물', description: "신라의 승려 **혜초**가 인도를 여행하고 쓴 기행문입니다. 당시 인도와 중앙아시아의 풍물, 종교, 문화를 생생하게 기록하여 세계적인 가치를 지닌 기록유산으로 평가받습니다. 현재 **프랑스 국립도서관**에 소장되어 있습니다.", icon: '📖' },
        { name: '🔥 김헌창의 난', type: 'city', category: '사건', description: "신라 하대에 일어난 대표적인 귀족 반란. 자신의 아버지가 왕이 되지 못한 것에 불만을 품고 일으킨 반란으로, 당시 중앙 정부의 통제력이 약화되고 **진골 귀족 간의 왕위 다툼**이 치열했음을 보여주는 사건입니다.", icon: '🔥' },
        { name: '🤔 6두품', type: 'city', category: '제도', description: "신라 **골품제**에서 왕족인 성골, 진골 다음의 신분. 학문적 능력은 뛰어났지만 높은 관직에 오르는 데 한계가 있었습니다. 신라 말, 이들은 새로운 사회를 꿈꾸며 **반신라 세력**으로 성장하여 훗날 고려 건국의 주역이 됩니다.", icon: '🤔' },
        { name: '🏞️ 상경용천부', type: 'city', category: '장소', description: "해동성국 **발해**의 수도. 당나라의 수도 장안성을 본떠 만든 계획도시로, 바둑판처럼 정연한 도로와 웅장한 궁궐이 있었던 국제적인 도시였습니다. 발해의 높은 문화 수준과 국력을 보여줍니다.", icon: '🏞️' },
        { name: '👑 대조영', type: 'city', category: '인물', description: "고구려 멸망 후, 흩어진 고구려 유민과 말갈족을 이끌고 **동모산**에서 **발해**를 건국한 영웅입니다. 그는 고구려의 기상과 문화를 계승하여 북방에 새로운 역사를 열었습니다.", icon: '👑' },
        { name: '🧱 정혜공주묘', type: 'city', category: '장소', description: "발해 문왕의 둘째 딸, 정혜공주의 무덤입니다. 굴식 돌방무덤 양식과 돌사자상 등은 발해가 **고구려를 계승**했음을 보여주는 중요한 증거입니다. 묘비명을 통해 발해의 역사 연구에 귀중한 자료를 제공합니다.", icon: '🧱' },
        { name: '🤝 솔빈부의 말', type: 'city', category: '유물', description: "발해의 특산품으로, **솔빈부**라는 특정 지역에서 생산된 말은 용맹하고 뛰어나기로 유명하여 당나라에 수출하는 주요 상품이었습니다. 이는 발해의 목축업이 매우 발달했음을 보여줍니다.", icon: '🤝' },
        { name: '🎨 이불병좌상', type: 'city', category: '유물', description: "두 부처가 나란히 앉아있는 모습을 표현한 발해의 불상입니다. 이러한 양식은 **고구려 불상의 영향**을 받은 것으로, 발해가 고구려 불교 문화를 계승했음을 보여주는 중요한 유물입니다.", icon: '🎨' },
        { name: '👑 무왕', type: 'city', category: '인물', description: "발해의 2대 왕으로, **'인안'**이라는 독자적인 연호를 사용하며 당나라와 대등한 국가임을 과시했습니다. 장군 **장문휴**를 보내 당나라의 등주를 공격하는 등 강력한 군사력으로 발해의 영토를 확장했습니다.", icon: '👑' },
        { name: '👑 선왕', type: 'city', category: '인물', description: "발해의 최전성기를 이끈 왕. 발해의 영토를 최대로 넓히고, 지방 제도를 정비하여 '**해동성국(바다 동쪽의 융성한 나라)**'이라 불리게 한 위대한 군주입니다.", icon: '👑' },
        { name: '🌊 발해의 대외교류', type: 'city', category: '사건', description: "발해는 당나라, 일본, 신라 등과 활발히 교류했습니다. 특히 일본과는 우호적인 관계를 유지하며 '**일본도**'라는 교역로를 이용했고, 신라와는 경쟁하면서도 교류하는 '**신라도**'가 있었습니다.", icon: '🌊' },
        { name: '📜 정효공주묘', type: 'city', category: '장소', description: "발해 문왕의 넷째 딸, 정효공주의 무덤입니다. **벽돌무덤** 양식과 **벽화**는 당나라 문화의 영향을 보여주며, 발해가 고구려 문화를 기반으로 국제적인 문화를 수용했음을 증명하는 중요한 유적입니다.", icon: '📜' },
        // FIX: Added missing type property
        { name: '멸망 거란의 침입', type: 'city', category: '사건', description: "10세기 초, 급격히 성장한 **거란(요나라)**의 침입으로 해동성국 발해는 허무하게 멸망하고 맙니다. 멸망 후 발해 유민들은 고려로 망명하거나 부흥 운동을 전개했습니다.", icon: '🔥' },
        { name: '🙏 원효', type: 'city', category: '인물', description: "신라의 위대한 승려. **'일체유심조(모든 것은 마음먹기에 달렸다)'**라는 깨달음을 얻고, 어려운 불교 교리를 '**나무아미타불**'만 외우면 극락에 갈 수 있다는 **아미타 신앙**으로 대중화시켜 불교를 널리 전파했습니다.", icon: '🙏' },
        { name: '📖 최치원', type: 'city', category: '인물', description: "신라 말기의 천재적인 학자. 12세에 당나라에 유학하여 빈공과에 급제하고 문장가로 명성을 떨쳤습니다. 신라로 돌아와 개혁을 주장했으나, 진골 귀족의 벽에 부딪혀 좌절하고 은둔 생활을 했습니다.", icon: '📖' },
        { name: '💨 풍수지리설', type: 'city', category: '문화', description: "땅의 모양을 보고 인간의 길흉화복을 점치는 사상. 신라 말 **도선**에 의해 널리 퍼졌습니다. 경주의 지덕이 쇠했다는 생각은 지방 호족들이 새로운 나라를 세우는 사상적 기반이 되었습니다.", icon: '💨' },
        { name: '👑 진성여왕', type: 'city', category: '인물', description: "신라의 마지막 여왕. 그녀의 시대에 **원종과 애노의 난** 등 농민 봉기가 전국적으로 일어나고 호족들이 성장하면서 신라는 멸망의 길로 접어들게 됩니다.", icon: '👑' },
        { name: '🌾 농민 봉기', type: 'city', category: '사건', description: "신라 말, 귀족들의 사치와 수탈, 그리고 계속되는 흉년으로 살기 어려워진 농민들이 전국 각지에서 봉기했습니다. **원종과 애노의 난**을 시작으로, 신라는 걷잡을 수 없는 혼란에 빠집니다.", icon: '🌾' },
        { name: '🏆 호족의 성장', type: 'city', category: '사건', description: "신라 말, 중앙 정부의 통제력이 약화되자 지방에서는 스스로를 '**성주**' 또는 '**장군**'이라 칭하는 강력한 세력, **호족**이 등장합니다. 이들은 훗날 후삼국 시대의 주역인 견훤, 궁예, 왕건의 기반이 됩니다.", icon: '🏆' },
        { name: '🗺️ 신라 5소경', type: 'city', category: '제도', description: "통일신라가 넓어진 영토를 효율적으로 다스리기 위해 수도 경주 외에 설치한 5개의 작은 수도(금관경, 남원경, 서원경, 중원경, 북원경). 지방의 중심지 역할을 하며 국가 발전에 기여했습니다.", icon: '🗺️' },
        { name: '⚔️ 매소성 전투', type: 'city', category: '전투', description: "삼국 통일 후, 한반도를 지배하려는 당나라의 야욕에 맞서 싸운 **나당 전쟁**의 결정적인 전투입니다. 이 전투의 승리로 신라는 당나라 군대를 대동강 이북으로 완전히 몰아내고 진정한 통일을 이룰 수 있었습니다.", icon: '⚔️' },
        { name: '🌊 기벌포 해전', type: 'city', category: '전투', description: "**매소성 전투**와 함께 나당 전쟁의 승리를 이끈 중요한 해전입니다. 금강 하구에서 신라 수군이 당나라 수군을 격파하여, 서해의 제해권을 장악하고 당의 보급로를 차단했습니다.", icon: '🌊' },
        { name: '📜 민정문서', type: 'city', category: '유물', description: "통일신라 시대의 **세금 징수** 기록 문서. 일본에서 발견되었으며, 당시 서원경(청주) 부근 4개 촌락의 인구, 토지, 과일나무 수까지 3년마다 상세히 기록했습니다. 이를 통해 신라의 정교한 행정 시스템을 엿볼 수 있습니다.", icon: '📜' },
        { name: '🎓 국학', type: 'city', category: '제도', description: "**신문왕**이 설립한 통일신라 최고의 국립 교육기관. 유교 경전을 가르쳐 왕에게 충성하는 인재를 양성하고, 왕권을 뒷받침하는 역할을 했습니다.", icon: '🎓' },
        { name: '💰 녹읍 폐지', type: 'city', category: '제도', description: "귀족에게 토지와 그 지역의 백성에 대한 노동력 징발권까지 주던 **녹읍**을 폐지하고, 대신 곡물만 수확할 수 있는 **관료전**을 지급한 신문왕의 개혁. 귀족의 경제적 기반을 약화시키고 왕권을 강화하기 위한 정책이었습니다.", icon: '💰' },
        { name: '🙏 의상', type: 'city', category: '인물', description: "원효와 함께 신라 불교를 이끈 고승. 당나라 유학 후, 모든 존재가 서로 조화를 이루고 있다는 **화엄 사상**을 널리 전파했습니다. 부석사를 창건하고 많은 제자를 길러내 화엄종을 발전시켰습니다.", icon: '🙏' },
        { name: '🛕 부석사', type: 'city', category: '장소', description: "의상대사가 화엄 사상을 전파하기 위해 창건한 사찰. 특히 **무량수전**은 우리나라에서 가장 아름다운 목조 건축물 중 하나로 손꼽히며, 유네스코 세계문화유산에 등재되었습니다.", icon: '🛕' },
        { name: '💎 울산항', type: 'city', category: '장소', description: "통일신라의 국제 무역항. 아라비아 상인들까지 드나들며 활발한 교역이 이루어졌습니다. **처용가**에 등장하는 처용이 바로 이슬람 상인이라는 설도 있습니다.", icon: '💎' },
        { name: '🎶 향가', type: 'city', category: '문화', description: "신라 시대에 불린 우리 고유의 노래. **서동요, 제망매가, 찬기파랑가** 등이 유명하며, 당시 사람들의 생각과 감정을 엿볼 수 있는 귀중한 문학 유산입니다.", icon: '🎶' },
        { name: '🤝 골품제', type: 'city', category: '제도', description: "신라 사회의 근간을 이룬 엄격한 신분 제도. **성골, 진골, 6두품~1두품**으로 나뉘어, 태어날 때부터 오를 수 있는 관직과 집의 크기까지 모든 것을 결정했습니다. 신라 발전의 원동력이었지만, 말기에는 사회 혼란의 원인이 되었습니다.", icon: '🤝' },
        { name: '⚔️ 장문휴', type: 'city', category: '인물', description: "발해 **무왕**의 명을 받아 수군을 이끌고 당나라의 **등주(산둥반도)**를 공격한 용맹한 장군. 이 공격은 발해가 당나라와 대등한 힘을 가진 자주적인 국가임을 보여주는 상징적인 사건입니다.", icon: '⚔️' },
        { name: '👑 문왕', type: 'city', category: '인물', description: "발해의 3대 왕. 당나라와 친선 관계를 맺고 문물을 받아들여 국가 체제를 정비했습니다. 수도를 중경에서 상경으로 옮기고, 자신을 황제라 칭하며 발해의 위상을 높였습니다.", icon: '👑' },
        { name: '📜 발해의 연호', type: 'city', category: '제도', description: "발해는 **천통(고왕), 인안(무왕), 대흥(문왕), 건흥(선왕)** 등 독자적인 연호를 사용하여 중국과 대등한 황제 국가임을 선포했습니다. 이는 발해의 강력한 자주 의식을 보여줍니다.", icon: '📜' },
        { name: '🏢 3성 6부', type: 'city', category: '제도', description: "발해가 당나라의 중앙 정치 제도를 받아들여 독자적으로 운영한 통치 조직. 명칭과 운영 방식에서 고구려의 전통을 계승하는 등 발해만의 특징을 보여줍니다.", icon: '🏢' },
        { name: '🧱 온돌', type: 'city', category: '문화', description: "구들장을 데워 방 전체를 따뜻하게 하는 우리 고유의 난방 방식. 발해의 상경성 궁궐터에서 온돌 장치가 발견되어, 발해가 고구려의 문화를 계승했음을 보여주는 중요한 증거가 됩니다.", icon: '🧱' },
        { name: '🤝 5경 15부 62주', type: 'city', category: '제도', description: "**선왕** 때 완성된 발해의 지방 행정 조직. 넓어진 영토를 효율적으로 다스리기 위해 5개의 수도(5경)와 주요 행정 구역을 설치했습니다. 발해의 전성기를 상징하는 제도입니다.", icon: '🤝' },
        { name: '🗿 돌사자상', type: 'city', category: '유물', description: "발해 **정혜공주묘**에서 출토된 돌사자상. 힘차고 생동감 있는 모습은 고구려의 기상을 그대로 이어받았음을 보여줍니다. 발해 조각 예술의 높은 수준을 보여주는 대표적인 작품입니다.", icon: '🗿' },
        { name: '🙏 발해의 불교', type: 'city', category: '문화', description: "발해는 불교를 숭상하여 많은 사찰과 불상을 만들었습니다. 특히 **이불병좌상**처럼 고구려의 양식을 계승한 불상은 발해 문화의 독자성과 계승성을 잘 보여줍니다.", icon: '🙏' },
        { name: '🔥 원종·애노의 난', type: 'city', category: '사건', description: "**진성여왕** 때 일어난 최초의 대규모 농민 봉기. 과도한 세금 징수에 저항하며 일어났으며, 이 봉기를 시작으로 전국 각지에서 농민들이 봉기하여 신라는 멸망의 길로 접어들게 됩니다.", icon: '🔥' },
        { name: '🤔 선종', type: 'city', category: '문화', description: "신라 하대에 유행한 불교의 한 종파. 교리 공부보다 **참선을 통한 깨달음**을 중시하여, 중앙 귀족보다 지방 호족과 백성들에게 큰 환영을 받았습니다. 이는 새로운 시대를 여는 사상적 기반이 되었습니다.", icon: '🤔' },
        { name: '🤝 발해 부흥 운동', type: 'city', category: '사건', description: "거란에 의해 멸망한 후, 발해의 유민들은 약 200년간 끈질기게 나라를 되찾기 위한 부흥 운동을 벌였습니다. 비록 실패했지만, 그들의 강인한 저항 정신은 역사에 깊이 새겨져 있습니다.", icon: '🤝' },
        { name: '💎 귀족들의 사치', type: 'city', category: '사건', description: "신라 말, 중앙 귀족들은 극심한 사치와 향락에 빠져 있었습니다. 집을 금으로 장식할 정도였으며, 이는 국가 재정을 어렵게 하고 백성들의 고통을 가중시켜 신라 멸망을 재촉하는 원인이 되었습니다.", icon: '💎' },
        { name: '🌾 적고적의 난', type: 'city', category: '사건', description: "붉은 바지를 입었다고 해서 이름 붙여진 도적 무리의 난. 원종·애노의 난 이후, 신라 말기의 혼란을 보여주는 대표적인 농민 봉기 중 하나입니다.", icon: '🌾' },
        { name: '🗺️ 대동강', type: 'city', category: '장소', description: "신라와 발해의 남쪽 국경선. 이 강을 경계로 남쪽에는 신라가, 북쪽에는 발해가 공존하며 남북국 시대를 이루었습니다.", icon: '🗺️' },
        { name: '🤝 신라방', type: 'city', category: '장소', description: "당나라에 살던 신라인들의 집단 거주지. 이곳을 중심으로 신라인들은 자치적으로 생활하며, 신라와 당나라 사이의 무역과 교류에서 중요한 역할을 했습니다.", icon: '🤝' },
        { name: '🐴 발해의 말', type: 'city', category: '유물', description: "발해의 주요 수출품이었던 말. 특히 솔빈부에서 나는 말은 품질이 뛰어나기로 유명했습니다. 이는 발해가 고구려의 기마 문화를 계승했음을 보여줍니다.", icon: '🐴' },
        { name: '🔥 백두산', type: 'city', category: '장소', description: "우리 민족의 영산. 10세기에 대규모 화산 폭발이 있었으며, 이 폭발이 발해 멸망에 영향을 주었다는 연구도 있습니다. 발해 역사와 깊은 관련이 있는 장소입니다.", icon: '🔥' },
        { name: '👑 경순왕', type: 'city', category: '인물', description: "신라의 마지막 왕(56대). 이미 기울어진 나라의 운명을 되돌릴 수 없음을 깨닫고, 백성의 피해를 줄이기 위해 평화적으로 고려의 왕건에게 나라를 넘겨주었습니다. 이로써 천년 왕국 신라는 막을 내립니다.", icon: '👑' },
    ],
    LATER_THREE_KINGDOMS: [
        { name: '🌾 농민 봉기', type: 'city', category: '사건', description: "신라 말, **진성여왕**의 실정과 계속되는 수탈로 농민들의 삶은 피폐해졌습니다. **원종과 애노의 난**을 시작으로 전국 각지에서 봉기가 일어나며, 신라의 통치력은 급격히 약화됩니다.", icon: '🌾' },
        { name: '🏆 호족의 성장', type: 'city', category: '사건', description: "중앙 정부의 힘이 약해진 틈을 타, 지방에서는 **성주**나 **장군**을 자칭하는 강력한 세력, **호족**이 등장합니다. 이들은 독자적인 군사력과 경제력을 바탕으로 새로운 시대의 주역으로 떠오릅니다.", icon: '🏆' },
        { name: '👑 견훤', type: 'city', category: '인물', description: "신라의 장군 출신으로, 지금의 전주인 **완산주**를 도읍으로 삼아 **후백제**를 건국합니다. 그는 '신라에 원수를 갚겠다'며 강한 적개심을 드러내며 후삼국 시대의 막을 엽니다.", icon: '👑' },
        { name: '👁️ 궁예', type: 'city', category: '인물', description: "신라 왕족 출신으로 알려진 인물. **송악(개성)**에서 세력을 키워 **후고구려**를 건국합니다. 스스로를 **미륵**이라 칭하며 '**관심법**'으로 사람의 마음을 읽는다고 주장하여 공포 정치를 펼칩니다.", icon: '👁️' },
        { name: '🏯 철원', type: 'city', category: '장소', description: "궁예가 국호를 **마진**, **태봉**으로 바꾸며 수도로 삼은 곳입니다. 새로운 이상 국가를 꿈꾸었던 궁예의 야망이 담긴 도시였지만, 그의 폭정으로 백성들의 고통이 깊어진 곳이기도 합니다.", icon: '🏯' },
        { name: '🤝 왕건', type: 'city', category: '인물', description: "송악의 유력한 해상 호족 출신. 궁예의 부하로 많은 공을 세웠으나, 궁예의 폭정이 심해지자 신하들의 추대를 받아 **고려**를 건국합니다. **포용 정책**으로 많은 호족과 백성의 지지를 얻습니다.", icon: '🤝' },
        { name: '🌊 나주 점령', type: 'city', category: '전투', description: "왕건이 수군을 이끌어 후백제의 배후 지역인 **나주**를 점령한 결정적인 사건입니다. 이로써 후백제는 큰 타격을 입고, 왕건은 후삼국 통일의 유리한 고지를 차지하게 됩니다.", icon: '🌊' },
        { name: '🔥 경주 침공', type: 'city', category: '사건', description: "후백제의 견훤이 신라의 수도 **경주**를 침공하여 경애왕을 죽게 하고, 포석정에서 연회를 즐기던 귀족들을 학살한 사건입니다. 이 사건으로 신라는 사실상 멸망 상태에 이릅니다.", icon: '🔥' },
        { name: '👑 경순왕', type: 'city', category: '인물', description: "견훤에 의해 왕위에 오른 신라의 마지막 왕. 이미 기울어진 나라를 되돌릴 수 없음을 깨닫고, 백성의 피해를 줄이기 위해 평화적으로 **고려 왕건에게 항복**합니다.", icon: '👑' },
        { name: '⚔️ 공산 전투', type: 'city', category: '전투', description: "견훤의 경주 침공 소식을 듣고 신라를 도우러 온 왕건이 대구 **팔공산**에서 후백제군에게 크게 패배한 전투. 왕건은 **신숭겸**, **김락** 등 충신들의 희생 덕분에 겨우 목숨을 구합니다.", icon: '⚔️' },
        { name: '🛡️ 신숭겸', type: 'city', category: '인물', description: "고려의 개국공신. **공산 전투**에서 왕건이 위기에 처하자, 왕의 옷을 대신 입고 싸우다 장렬히 전사하여 왕건을 구한 충절의 상징입니다.", icon: '🛡️' },
        { name: '🌊 고창 전투', type: 'city', category: '전투', description: "현재의 **안동** 지역에서 벌어진 전투. 공산 전투에서 패배했던 고려가 후백제에 결정적인 승리를 거두며, 후삼국 통일의 주도권을 완전히 가져오게 됩니다.", icon: '🌊' },
        { name: '🤝 발해 유민 포용', type: 'city', category: '사건', description: "거란에 멸망한 **발해**의 태자 대광현을 비롯한 수많은 유민이 고려로 망명해오자, 왕건은 이들을 따뜻하게 받아들입니다. 이는 고려가 **고구려를 계승**했음을 보여주는 상징적인 사건입니다.", icon: '🤝' },
        { name: '🔥 견훤의 귀부', type: 'city', category: '사건', description: "후백제의 왕위 계승 문제로 아들 **신검**에 의해 금산사에 감금되었던 견훤이 탈출하여, 숙적이었던 **왕건에게 항복**하는 충격적인 사건이 발생합니다.", icon: '🔥' },
        { name: '⚔️ 일리천 전투', type: 'city', category: '전투', description: "왕건이 이끄는 고려군과 신검의 후백제군이 벌인 후삼국 시대의 **마지막 전투**. 이 전투에서 고려가 승리하면서, 마침내 후삼국은 고려에 의해 통일됩니다.", icon: '⚔️' },
        { name: '🏆 후삼국 통일', type: 'city', category: '사건', description: "신라의 항복을 받고, 후백제를 멸망시킨 왕건이 마침내 분열되었던 나라를 다시 하나로 통일합니다. 이는 **새로운 민족 통일 국가, 고려**의 시작을 알리는 위대한 업적입니다.", icon: '🏆' },
        { name: '📜 훈요 10조', type: 'city', category: '제도', description: "태조 왕건이 후대 왕들이 지켜야 할 **10가지 가르침**을 남긴 유훈. 불교 숭상, 서경 중시, 북진 정책 등 고려 왕조의 기본 정책 방향을 제시했습니다.", icon: '📜' },
        { name: '🤝 사성 정책', type: 'city', category: '제도', description: "왕건이 지방 호족들을 자기편으로 만들기 위해 **왕씨 성**을 하사한 정책. 호족들을 왕의 친족으로 대우하며, 국가 통합에 기여하게 했습니다.", icon: '🤝' },
        { name: '💍 혼인 정책', type: 'city', category: '제도', description: "왕건이 전국의 유력한 호족들의 딸들과 결혼하여 **29명의 부인**을 둔 정책. 호족들과의 관계를 굳건히 하여 고려 건국 초기의 안정을 꾀했지만, 훗날 왕위 다툼의 원인이 되기도 합니다.", icon: '💍' },
        { name: '💰 흑창', type: 'city', category: '제도', description: "태조 왕건이 설치한 빈민 구제 기관. 고구려의 **진대법**을 계승한 것으로, 흉년에 굶주리는 백성들에게 곡식을 빌려주어 민심을 안정시키는 데 큰 역할을 했습니다.", icon: '💰' },
        { name: '🗺️ 북진 정책', type: 'city', category: '제도', description: "고구려의 옛 땅을 되찾으려는 태조 왕건의 의지. 수도를 개경에 정하고, **서경(평양)**을 중시하며, 북쪽으로 영토를 확장하려는 고려의 기본 정책이 되었습니다.", icon: '🗺️' },
        { name: '🤔 6두품의 활약', type: 'city', category: '인물', description: "신라의 골품제에 불만을 품었던 **6두품** 세력은 새로운 시대를 열고자 하는 왕건에게 적극적으로 협력합니다. **최언위, 최승로** 등 뛰어난 학자들이 고려의 건국과 발전에 큰 기여를 합니다.", icon: '🤔' },
        { name: '👑 태조 왕건', type: 'city', category: '인물', description: "고려를 건국하고 후삼국을 통일한 위대한 군주. **포용과 통합**의 리더십으로 분열된 민족을 하나로 묶어 새로운 시대를 열었습니다.", icon: '👑' },
        { name: '🤝 민생 안정책', type: 'city', category: '제도', description: "왕건은 백성들의 세금 부담을 **10분의 1**로 줄여주는 등, 오랜 전쟁으로 고통받던 백성들의 삶을 안정시키기 위한 정책을 펼쳐 큰 지지를 받았습니다.", icon: '🤝' },
        { name: '🏯 개경', type: 'city', category: '장소', description: "왕건의 고향이자 고려 500년의 수도. 예성강 하구에 위치하여 해상 활동에 유리했으며, **송악**이라 불리기도 했습니다.", icon: '🏯' },
        { name: '🗺️ 금성', type: 'city', category: '장소', description: "현재의 **나주**. 왕건이 궁예의 부하였을 때 점령하여 후삼국 통일의 결정적인 발판을 마련한 전략적 요충지입니다.", icon: '🗺️' },
        { name: '🏰 완산주', type: 'city', category: '장소', description: "견훤이 후백제를 세우고 수도로 삼은 곳으로, 현재의 **전주**입니다. 풍부한 곡창지대를 바탕으로 강력한 세력을 자랑했습니다.", icon: '🏰' },
        { name: '🪨 나주 동점문 밖 옹관묘', type: 'city', category: '유물', description: "나주 지역에서 발견된 독특한 무덤 양식. 이 지역을 기반으로 성장한 고대 **마한 세력**의 문화를 보여주며, 왕건이 해상 세력과 결합하는 데 중요한 기반이 되었음을 짐작게 합니다.", icon: '🪨' },
        { name: '⚔️ 아자개', type: 'city', category: '인물', description: "상주 지방의 호족이자 **견훤의 아버지**. 처음에는 신라에 충성했으나, 나중에는 아들 견훤의 후백제와 대립하다가 결국 고려 왕건에게 귀부합니다.", icon: '⚔️' },
        { name: '🤔 최승우', type: 'city', category: '인물', description: "신라 말의 6두품 출신 학자로 **후백제의 책사** 역할을 했습니다. 최치원과 함께 당나라에서 명성을 떨쳤으며, 견훤을 도와 고려에 맞서는 외교 문서를 작성했습니다.", icon: '🤔' },
        { name: '🙏 도선', type: 'city', category: '인물', description: "신라 말의 승려로, **풍수지리설**을 널리 퍼뜨렸습니다. '송악(개성)에서 새로운 왕이 나올 것'이라는 예언은 왕건이 고려를 건국하는 데 사상적 기반을 제공했습니다.", icon: '🙏' },
        { name: '🌊 양길', type: 'city', category: '인물', description: "신라 말 북원(원주) 지방에서 활동한 강력한 도적 세력의 우두머리. 처음에는 **궁예**를 부하로 받아들였으나, 세력이 커진 궁예에게 오히려 축출당하고 맙니다.", icon: '🌊' },
        { name: '👑 마진 & 태봉', type: 'city', category: '장소', description: "궁예가 세운 후고구려의 다른 이름들. 수도를 송악에서 **철원**으로 옮기고 국호를 바꾸며, 자신만의 독자적인 국가 체제를 만들고자 했던 궁예의 야망을 보여줍니다.", icon: '👑' },
        { name: '🤝 호족 연합', type: 'city', category: '사건', description: "고려는 중앙 집권 국가가 아니라, 태조 왕건을 중심으로 한 **지방 호족들의 연합체**라는 성격이 강했습니다. 왕건은 이들의 지지를 얻기 위해 혼인 정책, 사성 정책 등을 펼쳤습니다.", icon: '🤝' },
        { name: '🛡️ 유금필', type: 'city', category: '인물', description: "고려의 용맹한 장수. **북방의 여진족을 정벌**하고, 후백제와의 전투에서 수많은 공을 세우며 왕건의 통일 전쟁을 승리로 이끈 명장입니다.", icon: '🛡️' },
        { name: '⚔️ 대야성', type: 'city', category: '장소', description: "후백제와 신라의 국경에 있던 중요한 성. 견훤이 이곳을 함락시키면서 신라와의 관계가 돌이킬 수 없게 되었고, 이는 **김춘추**가 나당 동맹을 맺는 계기가 되기도 한 역사적인 장소입니다.", icon: '⚔️' },
        { name: '🤝 신라 구원', type: 'city', category: '사건', description: "왕건은 견훤의 침략으로 위기에 처한 신라에 대해 지속적으로 **우호적인 정책**을 펼쳤습니다. 이는 신라인들의 마음을 얻어, 훗날 경순왕이 평화적으로 항복하는 배경이 되었습니다.", icon: '🤝' },
        { name: '🔥 왕의 축출', type: 'city', category: '사건', description: "**궁예**는 폭정으로 민심을 잃어 부하들에게 쫓겨나 비참한 최후를 맞이하고, **견훤**은 아들 **신검**에 의해 왕위에서 쫓겨나는 등, 후삼국의 영웅들은 말년에 비극을 겪습니다.", icon: '🔥' },
        { name: '🤝 기인 제도', type: 'city', category: '제도', description: "태조 왕건이 지방 호족을 견제하기 위해 실시한 제도. 호족의 자제들을 수도인 **개경**에 와서 살게 하여, 사실상의 **인질**로 삼아 지방 세력의 반란을 막고자 했습니다.", icon: '🤝' },
        { name: '🗺️ 사심관 제도', type: 'city', category: '제도', description: "중앙의 고위 관리가 자신의 출신 지역을 다스리게 하는 제도. **신라 경순왕**을 경주의 사심관으로 임명한 것이 시초이며, 지방 세력을 통제하고 중앙의 영향력을 확대하기 위한 정책이었습니다.", icon: '🗺️' },
        { name: '🙏 불교 숭상', type: 'city', category: '문화', description: "왕건은 **연등회**와 **팔관회** 같은 불교 행사를 성대하게 열어, 불교를 통해 국민의 사상을 통합하고 왕실의 권위를 높이고자 했습니다. 이는 고려 시대 내내 중요한 전통이 됩니다.", icon: '🙏' },
        { name: '📜 역분전', type: 'city', category: '제도', description: "고려 건국 후, 왕건이 공을 세운 신하들에게 **공로와 인품**에 따라 토지를 나누어 준 제도. 이는 고려 시대 토지 제도의 시작이 되었습니다.", icon: '📜' },
        { name: '🤔 박술희', type: 'city', category: '인물', description: "태조 왕건의 충신 중 한 명. 왕건이 후계자를 걱정하자, 어린 혜종을 보호해달라는 유언을 받들었으나, 훗날 왕규의 난에 휘말려 비극적인 죽음을 맞이합니다.", icon: '🤔' },
        { name: '🔥 왕규의 난', type: 'city', category: '사건', description: "태조 왕건 사후, 외척이었던 **왕규**가 자신의 외손자를 왕으로 만들기 위해 일으킨 반란. 이 사건은 고려 초 **왕위 계승 다툼**이 얼마나 치열했는지를 보여줍니다.", icon: '🔥' },
        { name: '🌊 해상 세력', type: 'city', category: '제도', description: "왕건은 **송악(개성)**을 기반으로 한 강력한 해상 세력을 가지고 있었습니다. 이를 통해 중국과 교역하며 부를 쌓고, 서남해안을 장악하여 후백제를 견제할 수 있었습니다.", icon: '🌊' },
        { name: '🤝 거란 배척', type: 'city', category: '사건', description: "태조 왕건은 **'발해를 멸망시킨 거란과는 교류하지 말라'**는 유훈을 남깁니다. 거란 사신을 유배보내고 낙타를 굶겨 죽인 '**만부교 사건**'은 고려의 강력한 북진 정책과 고구려 계승 의식을 보여줍니다.", icon: '🤝' },
        { name: '🗺️ 서경', type: 'city', category: '장소', description: "고구려의 옛 수도였던 **평양**. 왕건은 이곳을 매우 중시하여 **북진 정책의 전진 기지**로 삼았으며, 후대 왕들에게 서경에 자주 머물 것을 당부했습니다.", icon: '🗺️' },
        { name: '👑 신검', type: 'city', category: '인물', description: "견훤의 아들로, 형제들을 제치고 왕위에 오르기 위해 아버지 견훤을 금산사에 가두는 **반란**을 일으킵니다. 그러나 민심을 잃고 결국 **일리천 전투**에서 왕건에게 패배하여 후백제를 멸망에 이르게 합니다.", icon: '👑' },
        { name: '🤝 신라 항복', type: 'city', category: '사건', description: "935년, 신라의 **경순왕**이 더 이상 나라를 유지할 수 없음을 깨닫고, 평화적으로 고려에 항복합니다. 이로써 **천년 왕국 신라**는 역사 속으로 사라집니다.", icon: '🤝' },
        { name: '🏛️ 고려 건국', type: 'city', category: '사건', description: "918년, 궁예의 폭정에 시달리던 신하들이 왕건을 새로운 왕으로 추대합니다. 왕건은 국호를 **고려**라 하고, 연호를 **천수**라 하여 **고구려를 계승**한 새로운 국가의 탄생을 선포합니다.", icon: '🏛️' },
        { name: '🏯 후백제 건국', type: 'city', category: '사건', description: "892년, 신라의 장수였던 견훤이 **무진주(광주)**를 점령하고, 900년에는 **완산주(전주)**에 도읍을 정하여 **후백제**를 건국합니다. 이로써 후삼국 시대의 막이 오릅니다.", icon: '🏯' },
        { name: '👑 후고구려 건국', type: 'city', category: '사건', description: "901년, 궁예가 **송악(개성)**에서 나라를 세우고 고구려의 부흥을 내세웁니다. 이후 수도를 **철원**으로 옮기고 국호를 **마진, 태봉**으로 바꾸며 강력한 국가를 건설하려 합니다.", icon: '👑' },
        { name: '🏰 금산사', type: 'city', category: '장소', description: "아들 신검에게 배신당한 **견훤**이 갇혔던 사찰. 견훤은 이곳을 탈출하여 그의 평생의 숙적이었던 왕건에게 귀부하는, 역사상 가장 극적인 사건의 무대가 됩니다.", icon: '🏰' },
        { name: '🏔️ 팔공산', type: 'city', category: '장소', description: "왕건이 견훤에게 대패한 **공산 전투**가 벌어진 곳. 오늘날 이곳에는 왕건을 구하고 전사한 **신숭겸 장군**의 유적지가 남아 그의 충절을 기리고 있습니다.", icon: '🏔️' },
        { name: '🤝 호족 세력', type: 'city', category: '인물', description: "신라 말, 각 지방을 실질적으로 지배했던 세력. **궁예, 견훤, 왕건** 모두 호족들의 지지를 기반으로 성장했으며, 고려 건국 이후에도 국가의 중요한 구성원으로 남았습니다.", icon: '🤝' },
        { name: '🌊 수군', type: 'city', category: '문화', description: "후삼국 시대의 승패를 가른 핵심적인 군사력. 특히 **왕건**은 강력한 수군을 바탕으로 서남해안을 장악하여 후백제를 압박하고, 통일의 기반을 마련했습니다.", icon: '🌊' },
    ],
    GORYEO: [
        { name: '👑 태조 왕건', type: 'city', category: '인물', description: "고려를 건국하고 후삼국을 통일한 위대한 군주. **포용과 통합**의 리더십으로 분열된 민족을 하나로 묶고, **북진 정책**과 **민생 안정책**으로 고려의 기틀을 마련했습니다.", icon: '👑' },
        { name: '📜 노비안검법', type: 'city', category: '제도', description: "**광종**이 실시한 개혁 정치. 억울하게 노비가 된 사람들을 조사하여 양인으로 해방시켜 주었습니다. 이는 왕권을 강화하고 호족의 경제적, 군사적 기반을 약화시키는 획기적인 정책이었습니다.", icon: '📜' },
        { name: '🎓 과거제', type: 'city', category: '제도', description: "**광종** 때 중국에서 온 **쌍기**의 건의로 처음 실시되었습니다. 시험을 통해 관리를 선발함으로써 왕에게 충성하는 새로운 세력을 등용하고, 왕권을 강화하는 데 큰 역할을 했습니다.", icon: '🎓' },
        { name: '🗣️ 서희', type: 'city', category: '인물', description: "거란의 1차 침입 때, 적장 **소손녕**과 담판을 벌여 오히려 **강동 6주**를 얻어낸 뛰어난 외교가입니다. 그의 '**외교 담판**'은 전쟁 없이 나라를 구하고 영토까지 확장한 우리 역사상 가장 빛나는 외교적 승리입니다.", icon: '🗣️' },
        { name: '🌊 강동 6주', type: 'city', category: '장소', description: "서희의 외교 담판으로 얻어낸 압록강 동쪽의 6개 성. 이곳을 확보함으로써 고려는 국경을 안정시키고, 여진족과의 관계에서 주도권을 잡을 수 있었습니다.", icon: '🌊' },
        { name: '⚔️ 강감찬', type: 'city', category: '인물', description: "거란의 3차 침입 때, 10만 대군을 이끌고 **귀주**에서 거란군을 전멸시킨 위대한 명장입니다. 그의 **귀주대첩** 승리로 고려는 거란과의 오랜 전쟁을 끝내고 동아시아에 평화를 가져왔습니다.", icon: '⚔️' },
        { name: '🛡️ 귀주대첩', type: 'city', category: '전투', description: "강감찬 장군이 이끈 고려군이 거란의 10만 대군을 크게 물리친 전투입니다. 우리 역사상 가장 위대한 대첩 중 하나로, 이 승리로 고려는 북방의 안정을 되찾고 전성기를 맞이하게 됩니다.", icon: '🛡️' },
        { name: '🤝 천리장성', type: 'city', category: '장소', description: "거란과 여진의 침입을 막기 위해 압록강에서 동해안까지 쌓은 거대한 성곽입니다. 고려의 강력한 국방 의지와 뛰어난 축성 기술을 보여주는 상징적인 건축물입니다.", icon: '🤝' },
        { name: '🔥 이자겸의 난', type: 'city', category: '사건', description: "고려 중기, 막강한 권력을 누리던 외척 **이자겸**이 왕위를 차지하기 위해 일으킨 반란. 이 사건으로 왕궁이 불타고 왕의 권위가 크게 실추되어, 고려 사회는 큰 혼란에 빠집니다.", icon: '🔥' },
        { name: '🗺️ 묘청의 서경 천도 운동', type: 'city', category: '사건', description: "승려 **묘청**이 '개경의 기운이 쇠했으니, 서경(평양)으로 수도를 옮겨야 한다'고 주장하며 일으킨 운동. **김부식**이 이끄는 개경파에 의해 진압되었으나, 자주적인 역사관을 보여준 사건으로 평가받습니다.", icon: '🗺️' },
        { name: '📖 삼국사기', type: 'city', category: '유물', description: "**김부식**이 왕의 명을 받아 편찬한 우리나라에 현존하는 가장 오래된 역사책. 유교적 합리주의 사관에 입각하여 삼국의 역사를 기록했습니다.", icon: '📖' },
        { name: '⚔️ 무신정변', type: 'city', category: '사건', description: "문신들로부터 차별받던 무신들이 **정중부, 이의방** 등을 중심으로 일으킨 쿠데타. 이 사건으로 많은 문신들이 살해당하고, 이후 약 100년간 무신들이 권력을 잡는 시대가 열립니다.", icon: '⚔️' },
        { name: '🔥 만적의 난', type: 'city', category: '사건', description: "무신정권기, **최충헌**의 노비였던 만적이 '왕후장상의 씨가 따로 있느냐'며 일으킨 신분 해방 운동. 비록 실패했지만, 노비들의 저항 의식을 보여준 중요한 사건입니다.", icon: '🔥' },
        { name: '🛡️ 삼별초', type: 'city', category: '제도', description: "무신정권의 군사적 기반이었던 특수 부대. 몽골에 대한 정부의 항복에 반대하여, **강화도, 진도, 제주도**로 옮겨가며 끝까지 항전하여 고려인의 자주 정신을 보여주었습니다.", icon: '🛡️' },
        { name: '📖 팔만대장경', type: 'city', category: '유물', description: "몽골의 침략을 **부처의 힘**으로 막아내고자 하는 염원을 담아 16년에 걸쳐 만든 목판 경전. 현재 **해인사**에 보관되어 있으며, 유네스코 세계기록유산으로 지정되었습니다.", icon: '📖' },
        { name: '🔥 몽골 침략', type: 'city', category: '전투', description: "13세기, 세계를 정복하던 몽골 제국이 고려를 30여 년간 7차례에 걸쳐 침략한 사건. 고려는 수도를 **강화도**로 옮기고 끈질기게 항전했으나, 국토는 크게 황폐화되었습니다.", icon: '⚔️' },
        { name: '🏺 상감청자', type: 'city', category: '유물', description: "고려의 독창적인 기술로 만든 세계적인 도자기. 표면을 파내고 다른 색의 흙을 메워 무늬를 만드는 **상감 기법**은 고려만의 독특하고 아름다운 예술 세계를 보여줍니다.", icon: '🏺' },
        { name: '📖 직지심체요절', type: 'city', category: '유물', description: "세계에서 가장 오래된 **금속 활자본**. 구텐베르크의 '42행 성서'보다 78년이나 앞선 것으로, 고려의 뛰어난 인쇄 기술을 보여주는 증거입니다. 유네스코 세계기록유산이며, 현재 **프랑스 국립도서관**에 있습니다.", icon: '📖' },
        { name: '🚢 벽란도', type: 'city', category: '장소', description: "고려의 국제 무역항. 예성강 하구에 위치하여, 송나라 상인은 물론 **아라비아 상인**들까지 드나들며 활발하게 교역했습니다. 이들을 통해 'Corea'라는 이름이 서양에 알려졌습니다.", icon: '🚢' },
        { name: '👑 공민왕', type: 'city', category: '인물', description: "원나라의 간섭에서 벗어나 고려의 자주성을 되찾으려 했던 개혁 군주. **반원 자주 정책**을 펼쳐 쌍성총관부를 공격하여 철령 이북의 땅을 되찾고, **신돈**을 등용하여 개혁을 추진했습니다.", icon: '👑' },
        { name: '🔥 홍건적과 왜구', type: 'city', category: '전투', description: "고려 말, 북쪽에서는 **홍건적**이, 남쪽에서는 **왜구**가 끊임없이 침략하여 나라가 큰 혼란에 빠졌습니다. 이들을 격퇴하는 과정에서 **최영, 이성계**와 같은 새로운 무인 세력이 성장하게 됩니다.", icon: '🔥' },
        { name: '🔥 최무선', type: 'city', category: '인물', description: "**화약**을 국산화하여 왜구를 격퇴하는 데 결정적인 기여를 한 과학자이자 장군. **화통도감**을 설치하고, 세계 최초의 함포인 **진포**를 이용하여 **진포대첩**에서 대승을 거두었습니다.", icon: '🔥' },
        { name: '🗡️ 이성계', type: 'city', category: '인물', description: "고려 말의 위대한 장군. **황산대첩**에서 왜구를 크게 물리쳐 백성의 영웅으로 떠올랐습니다. 그러나 **위화도 회군**을 통해 정치적 실권을 장악하고, 결국 조선을 건국하게 됩니다.", icon: '🗡️' },
        { name: '🔄️ 위화도 회군', type: 'city', category: '사건', description: "요동 정벌을 위해 압록강 위화도까지 갔던 **이성계**가 군사를 돌려 개경으로 돌아와 정권을 장악한 사건. 고려 왕조가 멸망하고 조선이 건국되는 결정적인 계기가 되었습니다.", icon: '🔄️' },
        { name: '💰 권문세족', type: 'city', category: '인물', description: "고려 후기, 원나라의 세력을 등에 업고 막대한 토지와 노비를 소유하며 권력을 휘두른 지배층. 이들의 횡포는 고려 사회의 모순을 심화시켰습니다.", icon: '💰' },
        { name: '🤔 신진사대부', type: 'city', category: '인물', description: "고려 말, 성리학을 바탕으로 사회 개혁을 주장하며 등장한 새로운 지식인 계층. **정도전, 정몽주** 등이 대표적이며, 이들은 이성계와 손잡고 조선 건국의 주역이 됩니다.", icon: '🤔' },
        { name: '❤️ 정몽주', type: 'city', category: '인물', description: "고려의 마지막 충신. 기울어가는 고려 왕조를 끝까지 지키려 했으나, 이방원의 **하여가**에 **단심가**로 답하고 선죽교에서 비참한 최후를 맞이합니다. 그의 충절은 오늘날까지도 높이 평가받습니다.", icon: '❤️' },
        { name: '👑 최영', type: 'city', category: '인물', description: "**'황금 보기를 돌같이 하라'**는 명언으로 유명한 고려의 명장. 수많은 전투에서 나라를 구했으나, 요동 정벌을 주장하다 이성계의 위화도 회군으로 제거됩니다.", icon: '👑' },
        { name: '🤝 전시과', type: 'city', category: '제도', description: "고려 시대 관리들에게 등급에 따라 토지를 나누어 준 제도. 곡물을 수확할 수 있는 **전지**와 땔감을 얻을 수 있는 **시지**를 주었습니다. 고려의 토지 제도의 근간이었습니다.", icon: '🤝' },
        { name: '👑 성종', type: 'city', category: '인물', description: "**최승로의 시무 28조**를 받아들여 유교 정치 이념을 확립한 왕. 지방에 **12목**을 설치하고 지방관을 파견하여 중앙 집권 체제를 강화했습니다.", icon: '👑' },
        { name: '📖 최승로', type: 'city', category: '인물', description: "고려 성종 때, 유교 정치의 중요성을 강조하는 **'시무 28조'**라는 개혁안을 올려 고려의 통치 체제 확립에 큰 영향을 준 신하입니다.", icon: '📖' },
        { name: '💰 건원중보', type: 'city', category: '유물', description: "고려 성종 때 만들어진 우리나라 최초의 화폐. 뒷면에 **'동국'**이라는 글자가 새겨져 있어, 고려의 자주성을 보여줍니다. 하지만 널리 사용되지는 못했습니다.", icon: '💰' },
        { name: '🌊 윤관과 별무반', type: 'city', category: '인물', description: "여진족을 정벌하기 위해 **윤관**의 건의로 창설된 특수 부대. 기병 중심의 **신기군**, 보병 중심의 **신보군**, 승려로 구성된 **항마군**으로 이루어져 있었습니다.", icon: '🌊' },
        { name: '🏰 동북 9성', type: 'city', category: '장소', description: "윤관이 이끄는 별무반이 여진족을 몰아내고 국경 지역에 쌓은 9개의 성. 그러나 여진족의 계속되는 반환 요구와 방어의 어려움으로 결국 1년 만에 돌려주게 됩니다.", icon: '🏰' },
        { name: '🤝 문벌 귀족', type: 'city', category: '인물', description: "고려 중기, 대대로 높은 관직을 차지하며 권력을 누린 지배층. **음서**와 **공음전**을 통해 자신들의 지위를 세습하며, 왕실과의 혼인을 통해 권력을 독점했습니다.", icon: '🤝' },
        { name: '📖 삼국유사', type: 'city', category: '유물', description: "승려 **일연**이 쓴 역사책. **단군 신화**를 비롯한 우리 고대의 신화와 설화, 불교 관련 이야기를 풍부하게 담고 있어, '삼국사기'와 함께 우리 고대사 연구의 중요한 자료입니다.", icon: '📖' },
        { name: '👑 최충헌', type: 'city', category: '인물', description: "무신정권기 4대 60여 년간 절대 권력을 휘두른 인물. **교정도감**이라는 최고 권력 기구를 설치하여 국정을 장악하고, 왕을 마음대로 교체할 만큼 강력한 힘을 가졌습니다.", icon: '👑' },
        { name: '🛡️ 강화도 천도', type: 'city', category: '사건', description: "몽골의 침략에 맞서기 위해, 고려 정부가 수도를 개경에서 **강화도**로 옮긴 사건. 섬이라는 지리적 이점을 이용해 몽골의 공격을 막아내며 약 30년간 항전했습니다.", icon: '🛡️' },
        { name: '🔥 처인성 전투', type: 'city', category: '전투', description: "몽골 2차 침입 때, 부곡민이었던 **김윤후**가 몽골의 총사령관 **살리타**를 화살로 쏘아 죽여 몽골군을 물리친 전투. 신분의 높고 낮음에 관계없이 모두가 힘을 합쳐 싸웠음을 보여줍니다.", icon: '🔥' },
        { name: '🤝 정동행성', type: 'city', category: '제도', description: "원래 원나라가 일본 원정을 위해 고려에 설치했던 기구. 일본 원정 실패 후에도 계속 남아 고려의 내정을 간섭하는 역할을 하여, 고려의 자주성을 크게 훼손했습니다.", icon: '🤝' },
        { name: '🤔 신돈', type: 'city', category: '인물', description: "**공민왕**의 신임을 얻어 개혁 정치를 추진한 승려. **전민변정도감**을 설치하여, 권문세족이 불법으로 빼앗은 토지와 노비를 원래 주인에게 돌려주려 했습니다.", icon: '🤔' },
        { name: '🌿 목화', type: 'city', category: '문화', description: "고려 말, **문익점**이 원나라에서 붓두껍에 목화씨를 숨겨와 우리나라에 전파했습니다. 이로써 백성들은 따뜻한 솜옷을 입을 수 있게 되어 의생활에 큰 변화를 가져왔습니다.", icon: '🌿' },
        { name: '⚔️ 황산대첩', type: 'city', category: '전투', description: "**이성계**가 황산(남원)에서 어린 장수 **아기바투**가 이끄는 왜구를 크게 물리친 전투. 이 승리로 이성계는 백성의 영웅으로 떠오르며, 새로운 시대의 주역으로 발돋움하게 됩니다.", icon: '⚔️' },
        { name: '💰 과전법', type: 'city', category: '제도', description: "고려 말, **신진사대부**의 경제적 기반을 마련하고 국가 재정을 확보하기 위해 실시한 토지 제도 개혁. 경기도의 토지를 전현직 관리에게 지급했습니다. 조선의 토지 제도로 이어집니다.", icon: '💰' },
        { name: '🤔 정도전', type: 'city', category: '인물', description: "조선 건국의 설계자. **성리학**을 바탕으로 한 재상 중심의 이상 국가를 꿈꾸었으며, 조선의 통치 이념과 제도의 기틀을 마련했습니다.", icon: '🤔' },
        { name: '🏯 개경', type: 'city', category: '장소', description: "고려 500년의 수도. 예성강 하구에 위치하여 해상 활동에 유리했으며, 국제 무역항 **벽란도**를 통해 세계와 교류하는 중심지였습니다.", icon: '🏯' },
        { name: '📖 제왕운기', type: 'city', category: '유물', description: "**이승휴**가 쓴 역사 서사시. 우리 역사를 중국사와 대등하게 서술하고, **단군**을 우리 민족의 시조로 기록하여 민족의 자주의식을 높였습니다.", icon: '📖' },
        { name: '🎶 고려 가요', type: 'city', category: '문화', description: "주로 평민들이 부르던 노래로, 남녀 간의 사랑 등 솔직하고 진솔한 감정을 담고 있습니다. **'가시리', '청산별곡'** 등이 유명하며, 우리 문학의 중요한 자산입니다.", icon: '🎶' },
        { name: '🔥 고려 멸망', type: 'city', category: '사건', description: "위화도 회군으로 권력을 잡은 이성계와 신진사대부가 **과전법**을 통해 경제권을 장악한 후, 1392년 공양왕을 폐위시키고 새로운 왕조를 열면서 500년 역사의 고려는 막을 내립니다.", icon: '🔥' },
        { name: '🤝 조세 제도', type: 'city', category: '제도', description: "고려의 세금은 토지세인 **조세**, 특산물을 내는 **공물**, 노동력을 제공하는 **역**으로 이루어져 있었습니다. 이 세금은 국가 운영의 기반이었습니다.", icon: '🤝' },
        { name: '💰 활구(은병)', type: 'city', category: '유물', description: "고려 시대에 사용된 은으로 만든 화폐. 우리나라 지형을 본떠 만들었다고 전해지며, 주로 고액 거래에 사용되었습니다.", icon: '💰' },
        { name: '🙏 의천', type: 'city', category: '인물', description: "고려 중기의 왕자이자 승려. 교리를 중시하는 **교종**을 중심으로, 참선을 중시하는 **선종**을 통합하려는 **'교관겸수'**를 주장하며 **천태종**을 창시했습니다.", icon: '🙏' },
        { name: '🤔 지눌', type: 'city', category: '인물', description: "무신정권기, 타락한 불교계를 개혁하기 위해 **수선사(송광사)**를 중심으로 **결사 운동**을 펼친 승려. **'정혜쌍수', '돈오점수'**를 주장하며 불교 혁신에 힘썼습니다.", icon: '🤔' },
        { name: '🔥 망이·망소이의 난', type: 'city', category: '사건', description: "무신정권기, 과도한 수탈에 저항하여 **공주 명학소**에서 일어난 하층민의 봉기. '소'는 차별받던 특수 행정 구역으로, 이들의 저항은 신분 해방 운동의 성격을 가집니다.", icon: '🔥' },
        { name: '🤝 원 간섭기', type: 'city', category: '사건', description: "몽골과의 전쟁에서 패배한 후, 약 80년간 원나라의 간섭을 받던 시기. 왕실 용어, 관직 이름 등이 격하되고, **변발**과 **몽골풍**이 유행하는 등 자주성에 큰 상처를 입었습니다.", icon: '🤝' },
        { name: '🤝 공녀', type: 'city', category: '제도', description: "원 간섭기에 고려의 젊은 여성들을 원나라에 바치던 슬픈 제도. 많은 여성들이 강제로 끌려가 고통을 겪었으며, 이로 인해 어린 나이에 결혼하는 **조혼** 풍습이 생겨났습니다.", icon: '🤝' },
    ],
    JOSEON: [
        { name: '👑 태조 이성계', type: 'city', category: '인물', description: "**위화도 회군**으로 고려를 무너뜨리고, 1392년 **조선**을 건국한 초대 왕. 수도를 **한양**으로 옮기고, **정도전**과 함께 새로운 왕조의 기틀을 마련했습니다.", icon: '👑' },
        { name: '🏛️ 경복궁', type: 'city', category: '장소', description: "조선 왕조의 법궁(정궁). **정도전**에 의해 '새 왕조가 큰 복을 누려 번영하라'는 의미로 이름 지어졌습니다. 조선의 중심이자 상징이었으나, 임진왜란 때 불타는 비운을 겪기도 했습니다.", icon: '🏛️' },
        { name: '👑 태종 이방원', type: 'city', category: '인물', description: "**왕자의 난**을 통해 왕위에 오른 강력한 군주. **6조 직계제**를 실시하여 왕권을 강화하고, **호패법**으로 인구를 파악하여 국가 재정과 군사력을 안정시켰습니다.", icon: '👑' },
        { name: '👑 세종대왕', type: 'city', category: '인물', description: "우리 역사상 가장 위대한 성군. **훈민정음** 창제, **집현전** 설치, **과학 기술 발전** 등 수많은 업적을 남겼습니다. 북쪽으로는 **4군 6진**을 개척하여 오늘날의 국경선을 확보했습니다.", icon: '👑' },
        { name: '✍️ 훈민정음', type: 'city', category: '유물', description: "**'백성을 가르치는 바른 소리'**라는 뜻으로, 세종대왕이 창제한 우리 고유의 문자. 배우기 쉬워 백성들이 자신의 생각을 자유롭게 표현할 수 있게 되었습니다. 유네스코 세계기록유산입니다.", icon: '✍️' },
        { name: '🔬 장영실', type: 'city', category: '인물', description: "세종 시대의 천재적인 과학 기술자. 노비 출신이었으나 재능을 인정받아 **자격루(물시계), 앙부일구(해시계), 혼천의, 측우기** 등 위대한 발명품들을 만들었습니다.", icon: '🔬' },
        { name: '🔥 계유정난', type: 'city', category: '사건', description: "**수양대군(세조)**이 어린 조카 단종의 왕위를 빼앗기 위해 김종서, 황보인 등 신하들을 죽이고 정권을 장악한 쿠데타. 이 사건은 훗날 **사육신**의 비극을 낳습니다.", icon: '🔥' },
        { name: '📖 경국대전', type: 'city', category: '유물', description: "**세조** 때 편찬하기 시작하여 **성종** 때 완성된 조선의 기본 법전. 정치, 경제, 사회, 문화 등 모든 분야의 규정을 담아, 조선이 **법치 국가**로 나아가는 기틀을 마련했습니다.", icon: '📖' },
        { name: '🤔 사림', type: 'city', category: '인물', description: "조선 중기, 향촌에서 학문 연구와 교육에 힘쓰던 선비 세력. **성종** 때 중앙 정치에 진출하여 기존의 **훈구 세력**과 대립하며, 네 차례의 **사화**를 겪는 등 시련을 겪습니다.", icon: '🤔' },
        { name: '⚔️ 임진왜란', type: 'city', category: '전투', description: "1592년, 일본의 **도요토미 히데요시**가 20만 대군을 이끌고 조선을 침략한 전쟁. 7년간 계속된 전쟁으로 국토는 황폐해졌지만, **이순신**을 비롯한 위대한 영웅들의 활약으로 나라를 지켜냈습니다.", icon: '⚔️' },
        { name: '🛡️ 이순신', type: 'city', category: '인물', description: "**'신에게는 아직 12척의 배가 남아있사옵니다'**. 임진왜란 당시, 불리한 상황 속에서도 뛰어난 전략과 리더십으로 일본 수군을 격파하여 나라를 구한 불멸의 영웅입니다.", icon: '🛡️' },
        { name: '🐢 거북선', type: 'city', category: '유물', description: "이순신 장군이 임진왜란 때 활용한 세계 최초의 철갑선. 강력한 방어력과 공격력을 바탕으로 **사천 해전**에서 처음 등장하여 일본 수군에게 공포의 대상이 되었습니다.", icon: '🐢' },
        { name: '🌊 한산도 대첩', type: 'city', category: '전투', description: "이순신 장군이 **학익진** 전술을 사용하여 일본 수군을 크게 물리친 전투. 이 승리로 조선은 남해의 제해권을 장악하고, 전쟁의 흐름을 바꾸는 결정적인 계기를 마련했습니다.", icon: '🌊' },
        { name: '👑 광해군', type: 'city', category: '인물', description: "임진왜란 이후의 혼란을 수습하고, **대동법**을 실시하여 백성의 부담을 줄여주는 등 뛰어난 정책을 펼쳤습니다. 명과 후금 사이에서 **중립 외교**를 펼쳤으나, **인조반정**으로 폐위됩니다.", icon: '👑' },
        { name: '🔥 병자호란', type: 'city', category: '전투', description: "청나라가 조선을 침략한 전쟁. **인조**는 **남한산성**에서 45일간 항전했으나, 결국 청 태종에게 항복하는 **삼전도의 굴욕**을 겪습니다.", icon: '🔥' },
        { name: '🤝 탕평책', type: 'city', category: '제도', description: "**영조**와 **정조**가 당파 싸움의 폐해를 막기 위해 실시한 정책. 특정 붕당에 치우치지 않고, 여러 붕당에서 인재를 고르게 등용하여 왕권을 강화하고 정치를 안정시키려 했습니다.", icon: '🤝' },
        { name: '👑 정조', type: 'city', category: '인물', description: "조선 후기의 위대한 개혁 군주. **규장각**을 설치하여 인재를 양성하고, 아버지 사도세자의 무덤이 있는 **수원 화성**을 건설했습니다. 그의 갑작스러운 죽음은 조선의 운명을 바꾸었습니다.", icon: '👑' },
        { name: '🏰 수원 화성', type: 'city', category: '장소', description: "**정조**가 **정약용**에게 명하여 건설한 계획도시이자 군사 기지. **거중기** 등 당시의 최첨단 과학 기술이 총동원되었으며, 아름다움과 실용성을 겸비하여 유네스코 세계문화유산으로 지정되었습니다.", icon: '🏰' },
        { name: '🤔 실학', type: 'city', category: '문화', description: "조선 후기, 성리학의 한계를 비판하며 등장한 새로운 학문. 농업 중심의 **중농학파(정약용)**와 상공업 중심의 **중상학파(박지원)**가 있었으며, 백성의 삶에 도움이 되는 실용적인 개혁을 주장했습니다.", icon: '🤔' },
        { name: '🗺️ 대동여지도', type: 'city', category: '유물', description: "**김정호**가 20여 년간 전국을 답사하며 만든 조선 최고의 지도. 산맥, 하천, 도로망 등이 매우 정밀하게 표시되어 있으며, 목판으로 제작되어 대량 생산이 가능했습니다. 조선의 지리학 수준을 보여주는 위대한 유산입니다.", icon: '🗺️' },
        { name: '🎨 김홍도와 신윤복', type: 'city', category: '문화', description: "조선 후기 서민들의 생활 모습을 생생하게 그려낸 대표적인 **풍속화가**. 김홍도는 **'씨름', '서당'** 등 서민들의 건강한 삶을, 신윤복은 **'미인도', '단오풍정'** 등 양반과 부녀자의 풍류를 섬세하게 표현했습니다.", icon: '🎨' },
        { name: '👑 흥선대원군', type: 'city', category: '인물', description: "어린 아들 고종을 대신하여 나라를 다스린 강력한 개혁가. **서원 철폐** 등 왕권 강화 정책을 펼쳤으나, 서양 세력의 접근을 막는 **척화비**를 세우는 등 **통상 수교 거부 정책**으로 조선의 근대화를 늦췄다는 비판도 받습니다.", icon: '👑' },
        { name: '🔥 동학농민운동', type: 'city', category: '사건', description: "**전봉준**을 중심으로 탐관오리의 수탈과 외세의 침략에 맞서 **'사람이 곧 하늘'**이라는 평등 사상을 내세우며 일어난 최대 규모의 농민 운동. 비록 실패했지만, 갑오개혁에 큰 영향을 주었습니다.", icon: '🔥' },
        { name: '📖 독립협회', type: 'city', category: '사건', description: "**서재필** 등이 중심이 되어 **독립문**을 세우고, **만민공동회**를 열어 백성들의 의견을 정치에 반영하려 했던 자주적 근대화 운동 단체. 우리나라 최초의 민주주의 운동으로 평가받습니다.", icon: '📖' },
        { name: '🏛️ 대한제국', type: 'city', category: '사건', description: "1897년, **고종**이 **환구단**에서 황제 즉위식을 거행하고 선포한 나라. 자주독립 국가임을 세계에 알리고자 했으나, 열강의 침략 속에서 실질적인 힘을 발휘하지는 못했습니다.", icon: '🏛️' },
        { name: '🤔 정약용', type: 'city', category: '인물', description: "조선 후기 실학을 집대성한 위대한 학자. 오랜 유배 생활 동안 **목민심서, 경세유표** 등 500여 권의 책을 저술하며, 사회 전반에 걸친 개혁 방안을 제시했습니다.", icon: '🤔' },
        { name: '🔥 명량해전', type: 'city', category: '전투', description: "정유재란 당시, 이순신 장군이 단 **12척**의 배로 133척의 일본 수군을 격파한 기적 같은 해전. 울돌목의 빠른 물살을 이용한 뛰어난 전술로 불가능을 가능으로 만든 위대한 승리입니다.", icon: '🔥' },
        { name: '📖 조선왕조실록', type: 'city', category: '유물', description: "조선 태조부터 철종까지 25대 472년간의 역사를 기록한 책. 왕이라도 볼 수 없었을 만큼 공정하고 객관적인 기록을 자랑하며, 그 가치를 인정받아 유네스코 세계기록유산으로 지정되었습니다.", icon: '📖' },
        { name: '🤔 정도전', type: 'city', category: '인물', description: "조선 건국의 설계자. **성리학**을 바탕으로 한 재상 중심의 이상 국가를 꿈꾸었으며, 조선의 통치 이념과 **경복궁**을 비롯한 제도의 기틀을 마련했습니다.", icon: '🤔' },
        { name: '🔥 왕자의 난', type: 'city', category: '사건', description: "조선 초, 왕위를 둘러싸고 왕자들이 벌인 피비린내 나는 싸움. **이방원(태종)**은 이 난을 통해 정도전 등 반대 세력을 제거하고 권력을 장악하여, 훗날 강력한 왕권을 구축하는 기반을 마련합니다.", icon: '🔥' },
        { name: '🤝 4대 사화', type: 'city', category: '사건', description: "조선 중기, **훈구 세력**이 새로운 정치 세력인 **사림**을 탄압한 네 차례의 큰 사건(무오, 갑자, 기묘, 을사사화). 이로 인해 많은 선비들이 희생되었으나, 사림은 서원과 향약을 기반으로 재기합니다.", icon: '🤝' },
        { name: '🤔 조광조', type: 'city', category: '인물', description: "급진적인 개혁을 추진한 사림의 대표주자. **현량과**를 통해 인재를 등용하고, '주초위왕(走肖爲王)'이라는 나뭇잎 글씨 조작 사건으로 결국 **기묘사화** 때 죽음을 맞이한 비운의 개혁가입니다.", icon: '🤔' },
        { name: '📖 서원', type: 'city', category: '장소', description: "조선 시대 지방 사림의 교육 기관이자 연구소. 제사를 지내고 학문을 연구하며 후학을 양성하여, 사림 세력의 중요한 기반이 되었습니다. **백운동 서원(소수서원)**이 최초의 서원입니다.", icon: '📖' },
        { name: '🛡️ 의병', type: 'city', category: '인물', description: "임진왜란 당시, 나라를 구하기 위해 자발적으로 일어난 백성들. **곽재우, 고경명** 등 의병장들의 활약은 관군에게 큰 힘이 되었으며, 조선의 강인한 저항 정신을 보여줍니다.", icon: '🛡️' },
        { name: '⚔️ 행주대첩', type: 'city', category: '전투', description: "**권율** 장군이 이끈 조선군이 부녀자들까지 힘을 합쳐 행주산성에서 일본군을 크게 물리친 전투. **한산도대첩, 진주대첩**과 함께 임진왜란 3대 대첩으로 꼽힙니다.", icon: '⚔️' },
        { name: '💰 대동법', type: 'city', category: '제도', description: "집집마다 특산물을 바치던 **공납**의 폐단을 막기 위해, 토지를 기준으로 **쌀, 옷감, 돈**으로 통일하여 내게 한 제도. **광해군** 때 시작하여 약 100년에 걸쳐 전국적으로 시행되었습니다.", icon: '💰' },
        { name: '🔥 인조반정', type: 'city', category: '사건', description: "서인 세력이 광해군의 **중립 외교**와 **폐모살제**를 명분으로 쿠데타를 일으켜 **인조**를 왕으로 세운 사건. 이로 인해 조선의 외교 정책은 친명배금으로 바뀌고, 결국 정묘호란과 병자호란의 원인이 됩니다.", icon: '🔥' },
        { name: '🗺️ 북벌 운동', type: 'city', category: '사건', description: "**효종** 때 병자호란의 치욕을 갚기 위해 청나라를 정벌하자는 운동이 일어났습니다. 비록 실행되지는 못했지만, 조선의 자주성을 회복하려는 의지를 보여주었습니다.", icon: '🗺️' },
        { name: '👑 영조', type: 'city', category: '인물', description: "조선 최장수 왕(52년 재위). 강력한 **탕평책**으로 붕당 갈등을 완화하고, 백성의 군역 부담을 줄여주는 **균역법**을 실시했습니다. 그러나 아들 **사도세자**를 뒤주에 가둬 죽게 한 비정한 아버지이기도 합니다.", icon: '👑' },
        { name: '📖 동의보감', type: 'city', category: '유물', description: "**허준**이 편찬한 동아시아 최고의 의학 서적. 질병의 예방과 치료법을 체계적으로 정리하여 의학 발전에 크게 기여했으며, 유네스코 세계기록유산으로 지정되었습니다.", icon: '📖' },
        { name: '🤔 박지원', type: 'city', category: '인물', description: "조선 후기 중상학파 실학의 대표주자. 청나라 여행 후 쓴 **'열하일기'**에서 수레와 화폐 사용의 중요성을 강조하고, 양반의 무능함을 풍자한 **'양반전'**을 썼습니다.", icon: '🤔' },
        { name: '💰 세도 정치', type: 'city', category: '사건', description: "정조 사후, **안동 김씨, 풍양 조씨** 등 소수의 외척 가문이 권력을 독점하던 시기. **매관매직**이 성행하고 삼정의 문란이 극심해져, 백성들의 삶은 매우 고통스러웠습니다.", icon: '💰' },
        { name: '🌾 삼정의 문란', type: 'city', category: '제도', description: "세도 정치 시기, 토지세(전정), 군역(군정), 환곡(환곡) 제도가 극심하게 문란해진 상황. 죽은 사람에게 세금을 매기는 등 관리들의 수탈이 극에 달해, **홍경래의 난, 임술 농민 봉기** 등 민란의 원인이 되었습니다.", icon: '🔥' },
        { name: '🔥 홍경래의 난', type: 'city', category: '사건', description: "세도 정치와 평안도 지역에 대한 차별에 저항하여 몰락 양반 **홍경래**가 일으킨 대규모 농민 봉기. 정주성에서 5개월간 저항했으나 결국 진압되었습니다.", icon: '🔥' },
        { name: '🙏 천주교 박해', type: 'city', category: '사건', description: "조선 후기, **인간 평등** 사상을 내세운 천주교가 전파되자, 조선 정부는 이를 사회 질서를 어지럽히는 사교로 규정하고 많은 신자들을 처형하는 등 혹독하게 탄압했습니다.", icon: '🙏' },
        { name: '🚢 신미양요', type: 'city', category: '전투', description: "**제너럴 셔먼호 사건**을 빌미로 미국이 강화도를 침략한 사건. 조선군은 **어재연** 장군의 지휘 아래 광성보에서 결사 항전했으나, 수적으로 열세하여 패배했습니다.", icon: '🚢' },
        { name: '🤝 강화도 조약', type: 'city', category: '사건', description: "일본 군함 **운요호**의 도발을 빌미로 맺어진 우리나라 최초의 근대적 조약이자 **불평등 조약**. 이 조약으로 부산 등 3개 항구가 개항되고, 조선은 본격적인 개화의 길을 걷게 됩니다.", icon: '🤝' },
        { name: '🔥 임오군란', type: 'city', category: '사건', description: "개화 정책에 대한 불만과 신식 군대와의 차별 대우에 분노한 **구식 군인**들이 일으킨 난. 이 사건을 계기로 청나라의 내정 간섭이 심해집니다.", icon: '🔥' },
        { name: '🏃 갑신정변', type: 'city', category: '사건', description: "**김옥균, 박영효** 등 급진개화파가 일본의 힘을 빌려 청나라로부터의 독립과 근대 국가 건설을 목표로 일으킨 **3일 천하**의 쿠데타. 실패했지만, 근대 국가를 향한 최초의 정치 개혁 운동이라는 의의를 가집니다.", icon: '🏃' },
        { name: '📜 갑오개혁', type: 'city', category: '사건', description: "동학농민운동을 계기로, 일본의 간섭 속에서 추진된 근대적 개혁. **신분제 폐지**, **과부의 재가 허용** 등 사회적으로는 큰 의미가 있었으나, 일본의 침략 의도가 숨어있었습니다.", icon: '📜' },
        { name: '🔪 을미사변', type: 'city', category: '사건', description: "일본이 친러 정책을 추진하던 **명성황후**를 경복궁에서 시해한 만행. 이 사건에 분노한 백성들은 **을미의병**을 일으켜 일본에 저항했습니다.", icon: '🔪' },
    ],
    MODERN_CONTEMPORARY: [
        { name: '🏛️ 대한제국', type: 'city', category: '사건', description: "1897년, **고종**이 **환구단**에서 황제 즉위식을 거행하고 선포한 나라. 자주독립 국가임을 세계에 알리고자 했으나, 열강의 침략 속에서 실질적인 힘을 발휘하지는 못했습니다.", icon: '🏛️' },
        { name: '📜 을사늑약', type: 'city', category: '사건', description: "1905년, 일본이 대한제국의 **외교권을 박탈**하기 위해 강제로 체결한 조약. 이로 인해 사실상 일본의 보호국이 되었으며, 많은 우국지사들이 자결하거나 항일 운동에 투신했습니다.", icon: '📜' },
        { name: '🕊️ 헤이그 특사', type: 'city', category: '사건', description: "을사늑약의 부당함을 알리기 위해 **고종 황제**가 네덜란드 헤이그 만국 평화 회의에 **이준, 이상설, 이위종**을 비밀리에 파견한 사건. 비록 실패했지만, 우리의 독립 의지를 세계에 보여주었습니다.", icon: '🕊️' },
        { name: '💰 국채보상운동', type: 'city', category: '사건', description: "일본에 진 빚 1,300만 원을 갚아 경제적 독립을 이루고자 대구에서 시작된 **범국민적 모금 운동**. 담배를 끊고 비녀를 팔아 나라 빚을 갚으려 했던 국민들의 애국심을 보여줍니다.", icon: '💰' },
        { name: '🔫 안중근 의사', type: 'city', category: '인물', description: "하얼빈 역에서 조선 침략의 원흉 **이토 히로부미**를 사살한 독립운동가. '**대한 독립의 소리가 천국에 들려오면, 나는 마땅히 춤추며 만세를 부를 것이다**'라는 유언을 남겼습니다.", icon: '🔫' },
        { name: '🇰🇷 3.1 운동', type: 'city', category: '사건', description: "1919년 3월 1일, '**대한 독립 만세**'를 외치며 시작된 거족적인 독립 만세 운동. 비폭력 평화 시위로 시작하여 전국, 전 계층으로 확산되어 우리의 독립 의지를 세계에 알렸습니다.", icon: '🇰🇷' },
        { name: '🔥 유관순 열사', type: 'city', category: '인물', description: "3.1 운동의 상징. 아우내 장터에서 만세 운동을 주도하다 체포되어, 서대문 형무소에서 모진 고문 속에서도 끝까지 독립 의지를 꺾지 않고 순국했습니다.", icon: '🔥' },
        { name: '🏢 대한민국 임시정부', type: 'city', category: '장소', description: "3.1 운동을 계기로, 독립 운동을 체계적으로 이끌기 위해 중국 **상하이**에 수립된 정부. **김구** 선생을 중심으로 광복까지 27년간 끈질기게 독립 투쟁을 전개했습니다.", icon: '🏢' },
        { name: '⚔️ 봉오동-청산리 전투', type: 'city', category: '전투', description: "**홍범도** 장군의 대한독립군과 **김좌진** 장군의 북로군정서가 만주에서 일본 정규군을 상대로 거둔 기적적인 대승리. 독립군의 사기를 크게 높인 빛나는 승전보였습니다.", icon: '⚔️' },
        { name: '🙏 윤동주 시인', type: 'city', category: '인물', description: "일제강점기, 별과 하늘을 노래하며 시대의 아픔과 부끄러움을 성찰한 민족 시인. '**죽는 날까지 하늘을 우러러 한 점 부끄럼이 없기를...**' 이라는 그의 시는 오늘날까지도 큰 울림을 줍니다.", icon: '🙏' },
        { name: '🎉 8.15 광복', type: 'city', category: '사건', description: "1945년 8월 15일, 35년간의 길고 어두웠던 일제강점기에서 벗어나 마침내 나라를 되찾은 감격적인 날입니다. 하지만 곧이어 남북 분단이라는 새로운 비극이 시작됩니다.", icon: '🎉' },
        { name: '⚔️ 6.25 전쟁', type: 'city', category: '전투', description: "1950년 6월 25일, 북한의 남침으로 시작된 동족상잔의 비극. 3년간의 전쟁으로 수백만 명의 사상자가 발생하고 국토는 폐허가 되었으며, 남북 분단의 아픔은 더욱 깊어졌습니다.", icon: '⚔️' },
        { name: '🌊 인천상륙작전', type: 'city', category: '전투', description: "6.25 전쟁 당시, **맥아더** 장군의 지휘 아래 유엔군이 감행한 기습 상륙 작전. 전쟁의 흐름을 단번에 뒤바꾸는 결정적인 계기가 되었습니다.", icon: '🌊' },
        { name: '✊ 4.19 혁명', type: 'city', category: '사건', description: "**이승만** 정부의 3.15 부정선거에 항의하여 학생들이 중심이 되어 일으킨 민주주의 혁명. 결국 대통령 하야를 이끌어내며, '**민주주의는 피를 먹고 자란다**'는 역사의 교훈을 남겼습니다.", icon: '✊' },
        { name: '🏭 한강의 기적', type: 'city', category: '사건', description: "전쟁의 폐허 속에서 불과 수십 년 만에 눈부신 경제 성장을 이룩한 대한민국 발전의 신화. **'우리도 한번 잘살아 보자'**는 국민들의 땀과 눈물이 만들어낸 위대한 결과입니다.", icon: '🏭' },
        { name: '🛣️ 경부고속도로', type: 'city', category: '장소', description: "서울과 부산을 잇는 대한민국 경제 발전의 대동맥. '한강의 기적'을 상징하는 대표적인 건축물로, 국가 경제 성장에 큰 기여를 했습니다.", icon: '🛣️' },
        { name: '🕊️ 5.18 민주화운동', type: 'city', category: '사건', description: "1980년 5월, 신군부의 쿠데타와 비상계엄 확대에 맞서 광주 시민과 학생들이 민주주의를 위해 저항했던 운동. 비록 무력으로 진압되었지만, 훗날 6월 민주항쟁의 밑거름이 되었습니다.", icon: '🕊️' },
        { name: '🗣️ 6월 민주항쟁', type: 'city', category: '사건', description: "1987년 6월, **박종철 고문치사 사건**과 **4.13 호헌 조치**를 계기로 전국적으로 일어난 민주화 운동. 결국 대통령 직선제 개헌을 이끌어내며, 대한민국 민주주의의 큰 진전을 이루었습니다.", icon: '🗣️' },
        { name: '🐯 88 서울 올림픽', type: 'city', category: '사건', description: "대한민국이 세계 무대의 중심으로 우뚝 섰음을 알린 국제적인 축제. '**손에 손잡고**'라는 주제가처럼 동서 화합의 장을 열었으며, 경제 성장과 국가 위상을 한 단계 끌어올렸습니다.", icon: '🐯' },
        { name: '💸 IMF 외환위기', type: 'city', category: '사건', description: "1997년, 국가 부도 위기에 처해 국제통화기금(IMF)으로부터 구제 금융을 지원받게 된 시련의 시기. 많은 기업이 도산하고 실업자가 급증하는 등 큰 고통을 겪었습니다.", icon: '💸' },
        { name: '🏅 금모으기 운동', type: 'city', category: '사건', description: "IMF 외환위기 극복을 위해 국민들이 자발적으로 장롱 속의 금을 나라에 내놓은 감동적인 운동. 전 세계를 놀라게 한 우리 국민의 저력과 애국심을 보여주었습니다.", icon: '🏅' },
        { name: '⚽ 2002 월드컵', type: 'city', category: '사건', description: "**'꿈은 이루어진다!'** 대한민국이 월드컵 4강 신화를 이룩한 기적의 순간. 붉은 악마의 열정적인 응원과 함께 온 국민이 하나 되었던 잊을 수 없는 축제였습니다.", icon: '⚽' },
        { name: '🤝 남북정상회담', type: 'city', category: '사건', description: "분단 이후 처음으로 남북의 정상이 만나 한반도의 평화와 통일을 논의한 역사적인 만남. 2000년 **김대중** 대통령과 김정일 국방위원장의 만남을 시작으로, 평화를 향한 노력이 이어지고 있습니다.", icon: '🤝' },
        { name: '🎤 K-POP', type: 'city', category: '문화', description: "전 세계를 무대로 활약하는 대한민국의 대중음악. 아이돌 그룹을 중심으로 한 중독성 있는 멜로디와 화려한 퍼포먼스로, 이제는 세계인이 즐기는 문화 현상이 되었습니다.", icon: '🎤' },
        { name: '📱 IT 강국', type: 'city', category: '문화', description: "세계 최고 수준의 인터넷 속도와 스마트폰 보급률을 자랑하는 정보기술(IT) 강국. 반도체, 스마트폰 등 첨단 기술 산업을 선도하며 세계 경제에 큰 영향력을 미치고 있습니다.", icon: '📱' },
        { name: '🎬 한류', type: 'city', category: '문화', description: "K-POP, 드라마, 영화 등 대한민국의 대중문화가 전 세계적으로 큰 인기를 얻는 현상. 문화의 힘으로 대한민국의 위상을 높이고, 세계인과 소통하고 있습니다.", icon: '🎬' },
        { name: '🏢 롯데월드타워', type: 'city', category: '장소', description: "대한민국의 랜드마크. 서울의 스카이라인을 바꾸어 놓은 초고층 빌딩으로, 대한민국의 발전된 건축 기술과 경제력을 상징합니다.", icon: '🏢' },
        { name: '🚄 KTX', type: 'city', category: '문화', description: "전국을 반나절 생활권으로 만든 대한민국 최초의 고속철도. 빠르고 편리한 교통수단으로 국민 생활에 큰 변화를 가져왔습니다.", icon: '🚄' },
        { name: '🌊 독도', type: 'city', category: '장소', description: "대한민국 동쪽 끝에 위치한 우리의 소중한 영토. 역사적, 지리적, 국제법적으로 명백한 우리 고유의 영토이며, 국가 주권의 상징입니다.", icon: '🌊' },
        { name: '🕊️ DMZ', type: 'city', category: '장소', description: "비무장지대(Demilitarized Zone). 6.25 전쟁 이후 남북한 사이에 설정된 군사적 완충 지대. 한반도 분단의 아픔을 상징하는 곳이자, 역설적으로 세계적인 생태 보전 지역이 되었습니다.", icon: '🕊️' },
    ],
};
